-- source/data/animations.lua
-- GENERATED by tools/canon/generate_animations_manifest.js — do not hand-edit.
-- Re-run when sprite animation specs change.
-- Phase 5 of canon-first migration plan.
--
-- Per-character animation state declarations:
--   frames        — explicit imagetable indices (or nil for non-imagetable system anims)
--   frameDuration — ticks per frame (AnimatedSprite tickStep equivalent)
--   loop          — bool
--   fallback      — state to switch to when play-once ends
--   blocks_input  — true halts d-pad reads while playing
--   bible_anim_id — link back to canon.animation_names id
--
-- Phase 9 sprite migration: Newb.lua loops over this table calling
-- addState dynamically instead of inline declarations.
-- Phase 7 validator: confirms frames[] within asset.frame_count.

local animations = {
    newb = {
        idle_south = {
            frames = {
                1,
                2
            },
            frameDuration = 30,
            loop = true,
            fallback = nil,
            blocks_input = false,
            bible_anim_id = "newb_idle_south"
        },
        walk_south = {
            frames = {
                3,
                4,
                5,
                6
            },
            frameDuration = 6,
            loop = true,
            fallback = "idle_south",
            blocks_input = false,
            bible_anim_id = "newb_walk_south"
        },
        idle_north = {
            frames = {
                7,
                12
            },
            frameDuration = 30,
            loop = true,
            fallback = nil,
            blocks_input = false,
            bible_anim_id = "newb_idle_north"
        },
        walk_north = {
            frames = {
                8,
                9,
                10,
                11
            },
            frameDuration = 6,
            loop = true,
            fallback = "idle_north",
            blocks_input = false,
            bible_anim_id = "newb_walk_north"
        },
        idle_east = {
            frames = {
                13,
                18
            },
            frameDuration = 30,
            loop = true,
            fallback = nil,
            blocks_input = false,
            bible_anim_id = "newb_idle_east"
        },
        walk_east = {
            frames = {
                14,
                15,
                16,
                17
            },
            frameDuration = 6,
            loop = true,
            fallback = "idle_east",
            blocks_input = false,
            bible_anim_id = "newb_walk_east"
        },
        idle_west = {
            frames = {
                19,
                24
            },
            frameDuration = 30,
            loop = true,
            fallback = nil,
            blocks_input = false,
            bible_anim_id = "newb_idle_west"
        },
        walk_west = {
            frames = {
                20,
                21,
                22,
                23
            },
            frameDuration = 6,
            loop = true,
            fallback = "idle_west",
            blocks_input = false,
            bible_anim_id = "newb_walk_west"
        },
        interact = {
            frames = {
                25
            },
            frameDuration = 30,
            loop = false,
            fallback = "idle_south",
            blocks_input = true,
            bible_anim_id = "newb_interact"
        },
        surprised = {
            frames = {
                26
            },
            frameDuration = 30,
            loop = false,
            fallback = "idle_south",
            blocks_input = false,
            bible_anim_id = "newb_surprised"
        }
    },
    system = {
        terminal_typewriter = {
            frames = nil,
            char_rate_ms = 28,
            loop = false,
            bible_anim_id = "terminal_typewriter",
            notes = "ComputerScene typewriter cadence — 28ms per char"
        },
        lockpick_pin_set = {
            frames = nil,
            loop = false,
            bible_anim_id = "lockpick_pin_set",
            notes = "flash + filled-pin render in pwnglove_lockpick state machine"
        },
        tyson_cabinet_attract = {
            frames = nil,
            loop = true,
            bible_anim_id = "tyson_cabinet_attract",
            notes = "GFXP dot-5 dither overlay during TYSON MODE banner"
        },
        coin_vault_zoom = {
            frames = nil,
            loop = false,
            bible_anim_id = "coin_vault_zoom",
            notes = "CoinVaultScene A-press transition grid -> closeup w/ rays"
        },
        crt_collapse = {
            frames = nil,
            loop = false,
            bible_anim_id = "crt_collapse",
            notes = "TV-B-Gone die animation (future IR wall scene)"
        }
    }
}

_G.animations_manifest = animations
return animations
