-- source/data/assets.lua
-- GENERATED by tools/canon/generate_assets_manifest.js — do not hand-edit.
-- Re-run whenever an asset is added/removed.
-- Phase 4 of canon-first migration plan.
--
-- Every shippable asset declared with id, type, path, dimensions,
-- frame_count, used_by_scene, used_by_character, priority.
-- Phase 7 validator confirms paths resolve + frame counts match
-- AnimatedSprite addState ranges.

local assets = {
    {
        id = "coin_0",
        type = "image",
        path = "images/coins/coin_0",
        file = "source/images/coins/coin_0.png",
        width = 48,
        height = 48,
        frame_count = 1,
        used_by_scene = {
            "CoinVaultScene"
        },
        used_by_character = nil,
        priority = "critical"
    },
    {
        id = "coin_0_large",
        type = "image",
        path = "images/coins/coin_0_large",
        file = "source/images/coins/coin_0_large.png",
        width = 200,
        height = 200,
        frame_count = 1,
        used_by_scene = {
            "CoinVaultScene"
        },
        used_by_character = nil,
        priority = "critical"
    },
    {
        id = "coin_1",
        type = "image",
        path = "images/coins/coin_1",
        file = "source/images/coins/coin_1.png",
        width = 48,
        height = 48,
        frame_count = 1,
        used_by_scene = {
            "CoinVaultScene"
        },
        used_by_character = nil,
        priority = "critical"
    },
    {
        id = "coin_1_large",
        type = "image",
        path = "images/coins/coin_1_large",
        file = "source/images/coins/coin_1_large.png",
        width = 200,
        height = 200,
        frame_count = 1,
        used_by_scene = {
            "CoinVaultScene"
        },
        used_by_character = nil,
        priority = "critical"
    },
    {
        id = "coin_2",
        type = "image",
        path = "images/coins/coin_2",
        file = "source/images/coins/coin_2.png",
        width = 48,
        height = 48,
        frame_count = 1,
        used_by_scene = {
            "CoinVaultScene"
        },
        used_by_character = nil,
        priority = "critical"
    },
    {
        id = "coin_2_large",
        type = "image",
        path = "images/coins/coin_2_large",
        file = "source/images/coins/coin_2_large.png",
        width = 200,
        height = 200,
        frame_count = 1,
        used_by_scene = {
            "CoinVaultScene"
        },
        used_by_character = nil,
        priority = "critical"
    },
    {
        id = "coin_3",
        type = "image",
        path = "images/coins/coin_3",
        file = "source/images/coins/coin_3.png",
        width = 48,
        height = 48,
        frame_count = 1,
        used_by_scene = {
            "CoinVaultScene"
        },
        used_by_character = nil,
        priority = "critical"
    },
    {
        id = "coin_3_large",
        type = "image",
        path = "images/coins/coin_3_large",
        file = "source/images/coins/coin_3_large.png",
        width = 200,
        height = 200,
        frame_count = 1,
        used_by_scene = {
            "CoinVaultScene"
        },
        used_by_character = nil,
        priority = "critical"
    },
    {
        id = "coin_locked",
        type = "image",
        path = "images/coins/coin_locked",
        file = "source/images/coins/coin_locked.png",
        width = 48,
        height = 48,
        frame_count = 1,
        used_by_scene = {
            "CoinVaultScene"
        },
        used_by_character = nil,
        priority = "critical"
    },
    {
        id = "newb_table_32_32",
        type = "imagetable",
        path = "images/newb-table-32-32",
        file = "source/images/newb-table-32-32.png",
        width = 32,
        height = 32,
        sheet_width = 128,
        sheet_height = 224,
        frame_count = 28,
        used_by_scene = {
            "BedroomScene",
            "PlaygroundScene",
            "SpriteTestScene"
        },
        used_by_character = "newb",
        priority = "critical"
    },
    {
        id = "newb",
        type = "image",
        path = "images/portraits/newb",
        file = "source/images/portraits/newb.png",
        width = 48,
        height = 56,
        frame_count = 1,
        used_by_scene = {
            "BedroomScene",
            "PhoneScene",
            "CoinVaultScene",
            "LockpickScene"
        },
        used_by_character = "newb",
        priority = "critical"
    },
    {
        id = "pwnglove_icon",
        type = "image",
        path = "images/pwnglove_icon",
        file = "source/images/pwnglove_icon.png",
        width = 200,
        height = 133,
        frame_count = 1,
        used_by_scene = {
            "TitleScene",
            "PlaygroundScene"
        },
        used_by_character = nil,
        priority = "critical"
    },
    {
        id = "hakcd_table_24_24",
        type = "imagetable",
        path = "images/tilesets/hakcd-table-24-24",
        file = "source/images/tilesets/hakcd-table-24-24.png",
        width = 24,
        height = 24,
        sheet_width = 192,
        sheet_height = 192,
        frame_count = 64,
        used_by_scene = {},
        used_by_character = nil,
        priority = "high"
    },
    {
        id = "title",
        type = "image",
        path = "images/title",
        file = "source/images/title.png",
        width = 400,
        height = 240,
        frame_count = 1,
        used_by_scene = {
            "TitleScene"
        },
        used_by_character = nil,
        priority = "critical"
    },
    {
        id = "lockpick_body",
        type = "image",
        path = "images/ui/lockpick_body",
        file = "source/images/ui/lockpick_body.png",
        width = 240,
        height = 100,
        frame_count = 1,
        used_by_scene = {
            "LockpickScene"
        },
        used_by_character = nil,
        priority = "critical"
    },
    {
        id = "bedroom_loop",
        type = "music",
        path = "sounds/music/bedroom_loop",
        file = "source/sounds/music/bedroom_loop.wav",
        width = nil,
        height = nil,
        duration_bytes = 15876250,
        used_by_scene = {
            "BedroomScene",
            "ComputerScene",
            "ModemScene",
            "PhoneScene"
        },
        used_by_character = nil,
        priority = "high"
    },
    {
        id = "coinvault_loop",
        type = "music",
        path = "sounds/music/coinvault_loop",
        file = "source/sounds/music/coinvault_loop.wav",
        width = nil,
        height = nil,
        duration_bytes = 11834728,
        used_by_scene = {
            "CoinVaultScene"
        },
        used_by_character = nil,
        priority = "high"
    },
    {
        id = "playground_loop",
        type = "music",
        path = "sounds/music/playground_loop",
        file = "source/sounds/music/playground_loop.wav",
        width = nil,
        height = nil,
        duration_bytes = 15802270,
        used_by_scene = {
            "PlaygroundScene"
        },
        used_by_character = nil,
        priority = "high"
    },
    {
        id = "title_loop",
        type = "music",
        path = "sounds/music/title_loop",
        file = "source/sounds/music/title_loop.wav",
        width = nil,
        height = nil,
        duration_bytes = 15879684,
        used_by_scene = {
            "TitleScene"
        },
        used_by_character = nil,
        priority = "high"
    },
    {
        id = "tyson_loop",
        type = "music",
        path = "sounds/music/tyson_loop",
        file = "source/sounds/music/tyson_loop.wav",
        width = nil,
        height = nil,
        duration_bytes = 7884020,
        used_by_scene = {
            "TysonScene"
        },
        used_by_character = nil,
        priority = "high"
    },
    {
        id = "coin_mint",
        type = "sfx",
        path = "sounds/sfx/coin_mint",
        file = "source/sounds/sfx/coin_mint.wav",
        width = nil,
        height = nil,
        duration_bytes = 15512,
        used_by_scene = {
            "CoinVaultScene"
        },
        used_by_character = nil,
        priority = "high"
    },
    {
        id = "coin_navigate_tick",
        type = "sfx",
        path = "sounds/sfx/coin_navigate_tick",
        file = "source/sounds/sfx/coin_navigate_tick.wav",
        width = nil,
        height = nil,
        duration_bytes = 1048,
        used_by_scene = {
            "CoinVaultScene"
        },
        used_by_character = nil,
        priority = "high"
    },
    {
        id = "coin_zoom_whoosh",
        type = "sfx",
        path = "sounds/sfx/coin_zoom_whoosh",
        file = "source/sounds/sfx/coin_zoom_whoosh.wav",
        width = nil,
        height = nil,
        duration_bytes = 9780,
        used_by_scene = {
            "CoinVaultScene"
        },
        used_by_character = nil,
        priority = "high"
    },
    {
        id = "lockpick_open",
        type = "sfx",
        path = "sounds/sfx/lockpick_open",
        file = "source/sounds/sfx/lockpick_open.wav",
        width = nil,
        height = nil,
        duration_bytes = 22126,
        used_by_scene = {
            "LockpickScene"
        },
        used_by_character = nil,
        priority = "high"
    },
    {
        id = "lockpick_pin_click_1",
        type = "sfx",
        path = "sounds/sfx/lockpick_pin_click_1",
        file = "source/sounds/sfx/lockpick_pin_click_1.wav",
        width = nil,
        height = nil,
        duration_bytes = 1400,
        used_by_scene = {
            "LockpickScene"
        },
        used_by_character = nil,
        priority = "high"
    },
    {
        id = "lockpick_pin_click_2",
        type = "sfx",
        path = "sounds/sfx/lockpick_pin_click_2",
        file = "source/sounds/sfx/lockpick_pin_click_2.wav",
        width = nil,
        height = nil,
        duration_bytes = 1400,
        used_by_scene = {
            "LockpickScene"
        },
        used_by_character = nil,
        priority = "high"
    },
    {
        id = "lockpick_pin_click_3",
        type = "sfx",
        path = "sounds/sfx/lockpick_pin_click_3",
        file = "source/sounds/sfx/lockpick_pin_click_3.wav",
        width = nil,
        height = nil,
        duration_bytes = 1400,
        used_by_scene = {
            "LockpickScene"
        },
        used_by_character = nil,
        priority = "high"
    },
    {
        id = "lockpick_pin_click_4",
        type = "sfx",
        path = "sounds/sfx/lockpick_pin_click_4",
        file = "source/sounds/sfx/lockpick_pin_click_4.wav",
        width = nil,
        height = nil,
        duration_bytes = 1400,
        used_by_scene = {
            "LockpickScene"
        },
        used_by_character = nil,
        priority = "high"
    },
    {
        id = "lockpick_pin_set",
        type = "sfx",
        path = "sounds/sfx/lockpick_pin_set",
        file = "source/sounds/sfx/lockpick_pin_set.wav",
        width = nil,
        height = nil,
        duration_bytes = 4488,
        used_by_scene = {
            "LockpickScene"
        },
        used_by_character = nil,
        priority = "high"
    },
    {
        id = "lockpick_snap",
        type = "sfx",
        path = "sounds/sfx/lockpick_snap",
        file = "source/sounds/sfx/lockpick_snap.wav",
        width = nil,
        height = nil,
        duration_bytes = 11102,
        used_by_scene = {
            "LockpickScene"
        },
        used_by_character = nil,
        priority = "high"
    },
    {
        id = "lockpick_tension_warn",
        type = "sfx",
        path = "sounds/sfx/lockpick_tension_warn",
        file = "source/sounds/sfx/lockpick_tension_warn.wav",
        width = nil,
        height = nil,
        duration_bytes = 17718,
        used_by_scene = {
            "LockpickScene"
        },
        used_by_character = nil,
        priority = "high"
    },
    {
        id = "pwnglove_boot",
        type = "sfx",
        path = "sounds/sfx/pwnglove_boot",
        file = "source/sounds/sfx/pwnglove_boot.wav",
        width = nil,
        height = nil,
        duration_bytes = 22128,
        used_by_scene = {
            "ComputerScene"
        },
        used_by_character = nil,
        priority = "high"
    },
    {
        id = "step_1",
        type = "sfx",
        path = "sounds/sfx/step_1",
        file = "source/sounds/sfx/step_1.wav",
        width = nil,
        height = nil,
        duration_bytes = 3130,
        used_by_scene = {
            "BedroomScene",
            "PlaygroundScene"
        },
        used_by_character = nil,
        priority = "high"
    },
    {
        id = "step_2",
        type = "sfx",
        path = "sounds/sfx/step_2",
        file = "source/sounds/sfx/step_2.wav",
        width = nil,
        height = nil,
        duration_bytes = 3130,
        used_by_scene = {
            "BedroomScene",
            "PlaygroundScene"
        },
        used_by_character = nil,
        priority = "high"
    },
    {
        id = "tyson_digit_commit",
        type = "sfx",
        path = "sounds/sfx/tyson_digit_commit",
        file = "source/sounds/sfx/tyson_digit_commit.wav",
        width = nil,
        height = nil,
        duration_bytes = 3606,
        used_by_scene = {
            "TysonScene"
        },
        used_by_character = nil,
        priority = "high"
    },
    {
        id = "tyson_digit_select",
        type = "sfx",
        path = "sounds/sfx/tyson_digit_select",
        file = "source/sounds/sfx/tyson_digit_select.wav",
        width = nil,
        height = nil,
        duration_bytes = 1180,
        used_by_scene = {
            "TysonScene"
        },
        used_by_character = nil,
        priority = "high"
    },
    {
        id = "tyson_winner",
        type = "sfx",
        path = "sounds/sfx/tyson_winner",
        file = "source/sounds/sfx/tyson_winner.wav",
        width = nil,
        height = nil,
        duration_bytes = 30066,
        used_by_scene = {
            "TysonScene"
        },
        used_by_character = nil,
        priority = "high"
    },
    {
        id = "launcher_card_pressed",
        type = "image",
        path = "assets/launcher/card-pressed",
        file = "source/assets/launcher/card-pressed.png",
        width = 350,
        height = 155,
        frame_count = 1,
        used_by_scene = {
            "_launcher_"
        },
        used_by_character = nil,
        priority = "critical"
    },
    {
        id = "launcher_card",
        type = "image",
        path = "assets/launcher/card",
        file = "source/assets/launcher/card.png",
        width = 350,
        height = 155,
        frame_count = 1,
        used_by_scene = {
            "_launcher_"
        },
        used_by_character = nil,
        priority = "critical"
    },
    {
        id = "launcher_launchImage",
        type = "image",
        path = "assets/launcher/launchImage",
        file = "source/assets/launcher/launchImage.png",
        width = 400,
        height = 240,
        frame_count = 1,
        used_by_scene = {
            "_launcher_"
        },
        used_by_character = nil,
        priority = "critical"
    }
}

_G.assets_manifest = assets
return assets
