-- source/data/canon.lua
-- GENERATED by tools/canon/generate_canon.js — do not hand-edit.
-- Re-run after tools/bible/parse_bible.js if the bible changes.
-- Phase 2 of canon-first migration plan.
--
-- Single source-of-truth for every id in the game. Scenes / sprites /
-- progression / asset loaders MUST read ids through this table, never
-- as bare strings.

local canon = {}

canon.game = {
    title = "HAKCD",
    genre = "cyberpunk-phreaker",
    tone  = "noir-grounded-comic-relief",
    timeline = "October 1998 through May 1999",
    core_premise = "A 17-year-old in suburban America, 1998, war-dials into a BBS run by a hacker who's been dead for two years. The mentor on the other end is an autonomous program written before he died, and it's been waiting for someone curious enough to pick up where he left off. ---"
}

canon.characters = {
    newb = {
        id = "newb",
        name = "newb",
        role = "protagonist",
        sprite_table = "images/newb-table-32-32",
        portrait = "images/portraits/newb",
        bible_section = "PROTAGONIST"
    },
    redhook = {
        id = "redhook",
        name = "RedHook",
        role = "supporting",
        cast_number = 13,
        sprite_table = nil,
        portrait = nil
    },
    mentor = {
        id = "mentor",
        name = "The Mentor / The Daemon",
        role = "mentor",
        sprite_table = nil,
        portrait = nil,
        bible_section = "THE MENTOR / THE DAEMON"
    },
    mom = {
        id = "mom",
        name = "Mom (offscreen voice)",
        role = "supporting",
        cast_number = 1,
        sprite_table = nil,
        portrait = nil
    },
    the_mentor = {
        id = "the_mentor",
        name = "The Mentor",
        role = "supporting",
        cast_number = 2,
        sprite_table = nil,
        portrait = nil
    },
    phoenixdown = {
        id = "phoenixdown",
        name = "PhoenixDown",
        role = "supporting",
        cast_number = 3,
        sprite_table = nil,
        portrait = nil
    },
    k0nsole = {
        id = "k0nsole",
        name = "k0nsole (revealed)",
        role = "supporting",
        cast_number = 10,
        sprite_table = nil,
        portrait = nil
    },
    gigglebutt69 = {
        id = "gigglebutt69",
        name = "GiGGLeBuTT69",
        role = "supporting",
        cast_number = 5,
        sprite_table = nil,
        portrait = nil
    },
    netranger94 = {
        id = "netranger94",
        name = "NetRanger94",
        role = "supporting",
        cast_number = 6,
        sprite_table = nil,
        portrait = nil
    },
    phractal = {
        id = "phractal",
        name = "phractal",
        role = "supporting",
        cast_number = 7,
        sprite_table = nil,
        portrait = nil
    },
    cr1m3l0rd = {
        id = "cr1m3l0rd",
        name = "Cr1M3L0RD",
        role = "supporting",
        cast_number = 8,
        sprite_table = nil,
        portrait = nil
    },
    xxx_d4rkn3ss_xxx = {
        id = "xxx_d4rkn3ss_xxx",
        name = "xXx_d4rkn3ss_xXx",
        role = "supporting",
        cast_number = 9,
        sprite_table = nil,
        portrait = nil
    },
    mrs_kowalski = {
        id = "mrs_kowalski",
        name = "Mrs. Kowalski",
        role = "supporting",
        cast_number = 11,
        sprite_table = nil,
        portrait = nil
    },
    aegis_tech_support_agent = {
        id = "aegis_tech_support_agent",
        name = "Aegis Tech Support Agent (no name)",
        role = "supporting",
        cast_number = 12,
        sprite_table = nil,
        portrait = nil
    },
    the_mentor_s_wife = {
        id = "the_mentor_s_wife",
        name = "The Mentor's wife (briefly mentioned in a found photo)",
        role = "supporting",
        cast_number = 14,
        sprite_table = nil,
        portrait = nil
    },
    cory_k = {
        id = "cory_k",
        name = "Cory K",
        role = "supporting",
        cast_number = 15,
        sprite_table = nil,
        portrait = nil
    }
}

canon.rooms = {
    sc01 = {
        id = "sc01",
        bible_name = "Bedroom (recurring hub)",
        act = "Act 1: The Boards (8 beats, 5 locations)",
        is_story_room = true,
        ldtk_level = "Bedroom"
    },
    sc02 = {
        id = "sc02",
        bible_name = "DEADLINE BBS",
        act = "Act 1: The Boards (8 beats, 5 locations)",
        is_story_room = true,
        ldtk_level = nil
    },
    sc03 = {
        id = "sc03",
        bible_name = "War dialer interface",
        act = "Act 1: The Boards (8 beats, 5 locations)",
        is_story_room = true,
        ldtk_level = nil
    },
    sc04 = {
        id = "sc04",
        bible_name = "Corporate BBS (PhoenixDown)",
        act = "Act 1: The Boards (8 beats, 5 locations)",
        is_story_room = true,
        ldtk_level = nil
    },
    sc05 = {
        id = "sc05",
        bible_name = "The phone bill cutscene",
        act = "Act 1: The Boards (8 beats, 5 locations)",
        is_story_room = true,
        ldtk_level = nil
    },
    sc06 = {
        id = "sc06",
        bible_name = "AOL signup cutscene",
        act = "Act 2: The Garden (10 beats, 6 locations)",
        is_story_room = true,
        ldtk_level = nil
    },
    sc07 = {
        id = "sc07",
        bible_name = "AOL Buddy List / Mail / Chat hub",
        act = "Act 2: The Garden (10 beats, 6 locations)",
        is_story_room = true,
        ldtk_level = nil
    },
    sc08 = {
        id = "sc08",
        bible_name = "#warez_lobby",
        act = "Act 2: The Garden (10 beats, 6 locations)",
        is_story_room = true,
        ldtk_level = nil
    },
    sc09 = {
        id = "sc09",
        bible_name = "#cyber_lounge",
        act = "Act 2: The Garden (10 beats, 6 locations)",
        is_story_room = true,
        ldtk_level = nil
    },
    sc10 = {
        id = "sc10",
        bible_name = "#phreak_kingdom",
        act = "Act 2: The Garden (10 beats, 6 locations)",
        is_story_room = true,
        ldtk_level = nil
    },
    sc11 = {
        id = "sc11",
        bible_name = "#h_p_v_a_c",
        act = "Act 2: The Garden (10 beats, 6 locations)",
        is_story_room = true,
        ldtk_level = nil
    },
    sc12 = {
        id = "sc12",
        bible_name = "#private_chan_7",
        act = "Act 2: The Garden (10 beats, 6 locations)",
        is_story_room = true,
        ldtk_level = nil
    },
    sc13 = {
        id = "sc13",
        bible_name = "ICQ window (overlay)",
        act = "Act 2: The Garden (10 beats, 6 locations)",
        is_story_room = true,
        ldtk_level = nil
    },
    sc14 = {
        id = "sc14",
        bible_name = "Bedroom (return)",
        act = "Act 3: The Wires (8 beats, 7 locations)",
        is_story_room = true,
        ldtk_level = nil
    },
    sc15 = {
        id = "sc15",
        bible_name = "Greyhound station payphone bank",
        act = "Act 3: The Wires (8 beats, 7 locations)",
        is_story_room = true,
        ldtk_level = nil
    },
    sc16 = {
        id = "sc16",
        bible_name = "k0nsole conversation",
        act = "Act 3: The Wires (8 beats, 7 locations)",
        is_story_room = true,
        ldtk_level = nil
    },
    sc17 = {
        id = "sc17",
        bible_name = "Bell pedestal in suburban yard, 2am",
        act = "Act 3: The Wires (8 beats, 7 locations)",
        is_story_room = true,
        ldtk_level = nil
    },
    sc18 = {
        id = "sc18",
        bible_name = "Telco switching office service entrance",
        act = "Act 3: The Wires (8 beats, 7 locations)",
        is_story_room = true,
        ldtk_level = nil
    },
    sc19 = {
        id = "sc19",
        bible_name = "Aegis network reconnaissance",
        act = "Act 3: The Wires (8 beats, 7 locations)",
        is_story_room = true,
        ldtk_level = nil
    },
    sc20 = {
        id = "sc20",
        bible_name = "Aegis tech support phone call",
        act = "Act 3: The Wires (8 beats, 7 locations)",
        is_story_room = true,
        ldtk_level = nil
    },
    sc21 = {
        id = "sc21",
        bible_name = "Inside the Aegis dev network",
        act = "Act 4: The Game (6 beats, 4 locations)",
        is_story_room = true,
        ldtk_level = nil
    },
    sc22 = {
        id = "sc22",
        bible_name = "RedHook's chatroom",
        act = "Act 4: The Game (6 beats, 4 locations)",
        is_story_room = true,
        ldtk_level = nil
    },
    sc23 = {
        id = "sc23",
        bible_name = "Release decision scene",
        act = "Act 4: The Game (6 beats, 4 locations)",
        is_story_room = true,
        ldtk_level = nil
    },
    sc24 = {
        id = "sc24",
        bible_name = "Exfiltration",
        act = "Act 4: The Game (6 beats, 4 locations)",
        is_story_room = true,
        ldtk_level = nil
    },
    sc25 = {
        id = "sc25",
        bible_name = "2002. Older protagonist's apartment",
        act = "Coda",
        is_story_room = true,
        ldtk_level = nil
    },
    sc26 = {
        id = "sc26",
        bible_name = "SecKC at Knuckleheads (post-credits coda)",
        act = "Coda",
        is_story_room = true,
        ldtk_level = nil
    },
    title = {
        id = "title",
        bible_name = "Title Splash",
        act = nil,
        is_story_room = false,
        ldtk_level = nil
    },
    playground = {
        id = "playground",
        bible_name = "PWNGLOVE MODE (sandbox)",
        act = nil,
        is_story_room = false,
        ldtk_level = "Playground"
    }
}

canon.scenes = {
    TitleScene = {
        id = "TitleScene",
        class = "TitleScene",
        room = "title",
        parent = nil,
        kind = "splash"
    },
    BedroomScene = {
        id = "BedroomScene",
        class = "BedroomScene",
        room = "sc01",
        parent = nil,
        kind = "room"
    },
    ComputerScene = {
        id = "ComputerScene",
        class = "ComputerScene",
        room = "sc01",
        parent = "BedroomScene",
        kind = "modal"
    },
    ModemScene = {
        id = "ModemScene",
        class = "ModemScene",
        room = "sc01",
        parent = "BedroomScene",
        kind = "modal"
    },
    PhoneScene = {
        id = "PhoneScene",
        class = "PhoneScene",
        room = "sc01",
        parent = "BedroomScene",
        kind = "modal"
    },
    PlaygroundScene = {
        id = "PlaygroundScene",
        class = "PlaygroundScene",
        room = "playground",
        parent = nil,
        kind = "room"
    },
    LockpickScene = {
        id = "LockpickScene",
        class = "LockpickScene",
        room = "playground",
        parent = "PlaygroundScene",
        kind = "minigame"
    },
    TysonScene = {
        id = "TysonScene",
        class = "TysonScene",
        room = "playground",
        parent = "PlaygroundScene",
        kind = "minigame"
    },
    CoinVaultScene = {
        id = "CoinVaultScene",
        class = "CoinVaultScene",
        room = "playground",
        parent = "PlaygroundScene",
        kind = "overlay"
    },
    SpriteTestScene = {
        id = "SpriteTestScene",
        class = "SpriteTestScene",
        room = nil,
        parent = nil,
        kind = "dev_only"
    }
}

canon.objects = {
    computer = {
        id = "computer",
        room = "sc01",
        is_hotspot = true,
        launches = "ComputerScene",
        label = "USE COMPUTER"
    },
    modem = {
        id = "modem",
        room = "sc01",
        is_hotspot = true,
        launches = "ModemScene",
        label = "USE MODEM"
    },
    phone = {
        id = "phone",
        room = "sc01",
        is_hotspot = true,
        launches = "PhoneScene",
        label = "ANSWER PHONE"
    },
    bed = {
        id = "bed",
        room = "sc01",
        is_hotspot = true,
        launches = nil,
        label = "SLEEP",
        sleeps = true,
        transitions_to = "PlaygroundScene"
    },
    lockpick_station = {
        id = "lockpick_station",
        room = "playground",
        is_hotspot = true,
        launches = "LockpickScene",
        label = "LOCKPICK"
    },
    tyson_cabinet = {
        id = "tyson_cabinet",
        room = "playground",
        is_hotspot = true,
        launches = "TysonScene",
        label = "TYSON"
    },
    coin_vault = {
        id = "coin_vault",
        room = "playground",
        is_hotspot = true,
        launches = "CoinVaultScene",
        label = "COIN VAULT"
    },
    rfid_pedestal = {
        id = "rfid_pedestal",
        room = "playground",
        is_hotspot = true,
        launches = nil,
        label = "RFID",
        placeholder = true
    },
    payphone = {
        id = "payphone",
        room = "playground",
        is_hotspot = true,
        launches = nil,
        label = "PAYPHONE",
        placeholder = true
    },
    ir_wall = {
        id = "ir_wall",
        room = "playground",
        is_hotspot = true,
        launches = nil,
        label = "IR WALL",
        placeholder = true
    },
    gravity_arena = {
        id = "gravity_arena",
        room = "playground",
        is_hotspot = true,
        launches = nil,
        label = "GRAVITY",
        placeholder = true
    },
    subghz_tuner = {
        id = "subghz_tuner",
        room = "playground",
        is_hotspot = true,
        launches = nil,
        label = "SUBGHZ",
        placeholder = true
    },
    portal_pedestal = {
        id = "portal_pedestal",
        room = "playground",
        is_hotspot = true,
        launches = nil,
        label = "PORTAL",
        placeholder = true
    }
}

canon.dialogue_ids = {
    mom_intro = {
        id = "mom_intro",
        speaker = "mom",
        triggered_by_object = "phone",
        scene = "PhoneScene",
        lines_count = 5
    },
    bbs_boot_sequence = {
        id = "bbs_boot_sequence",
        speaker = "system",
        triggered_by_object = "computer",
        scene = "ComputerScene",
        lines_count = 3
    },
    modem_war_dialer = {
        id = "modem_war_dialer",
        speaker = "system",
        triggered_by_object = "modem",
        scene = "ModemScene",
        lines_count = 14
    },
    coin_zero_welcome = {
        id = "coin_zero_welcome",
        speaker = "newb",
        triggered_by_object = "coin_vault",
        scene = "CoinVaultScene"
    },
    tyson_already = {
        id = "tyson_already",
        speaker = "system",
        triggered_by_object = "tyson_cabinet",
        scene = "TysonScene",
        when = "tyson_unlock==true"
    }
}

canon.state_flags = {
    tyson_unlock = {
        id = "tyson_unlock",
        persisted = true,
        default = false,
        set_by = {
            "TysonScene"
        },
        read_by = {
            "TysonScene",
            "PlaygroundScene",
            "BedroomScene"
        }
    },
    pwnglove_mode_complete = {
        id = "pwnglove_mode_complete",
        persisted = true,
        default = false,
        set_by = {
            "PlaygroundScene"
        },
        read_by = {
            "PlaygroundScene"
        }
    },
    current_act = {
        id = "current_act",
        persisted = true,
        default = 1,
        set_by = {},
        read_by = {
            "BedroomScene",
            "PlaygroundScene"
        }
    },
    coin_0_status = {
        id = "coin_0_status",
        persisted = true,
        default = "minted",
        set_by = {
            "CoinVaultScene"
        },
        read_by = {
            "CoinVaultScene"
        }
    },
    coin_1_status = {
        id = "coin_1_status",
        persisted = true,
        default = "available",
        set_by = {
            "CoinVaultScene"
        },
        read_by = {
            "CoinVaultScene"
        }
    },
    coin_2_status = {
        id = "coin_2_status",
        persisted = true,
        default = "available",
        set_by = {
            "CoinVaultScene"
        },
        read_by = {
            "CoinVaultScene"
        }
    },
    coin_3_status = {
        id = "coin_3_status",
        persisted = true,
        default = "locked",
        set_by = {
            "CoinVaultScene"
        },
        read_by = {
            "CoinVaultScene"
        }
    },
    coin_4_status = {
        id = "coin_4_status",
        persisted = true,
        default = "locked",
        set_by = {
            "CoinVaultScene"
        },
        read_by = {
            "CoinVaultScene"
        }
    },
    coin_5_status = {
        id = "coin_5_status",
        persisted = true,
        default = "locked",
        set_by = {
            "CoinVaultScene"
        },
        read_by = {
            "CoinVaultScene"
        }
    },
    coin_6_status = {
        id = "coin_6_status",
        persisted = true,
        default = "locked",
        set_by = {
            "CoinVaultScene"
        },
        read_by = {
            "CoinVaultScene"
        }
    },
    coin_7_status = {
        id = "coin_7_status",
        persisted = true,
        default = "locked",
        set_by = {
            "CoinVaultScene"
        },
        read_by = {
            "CoinVaultScene"
        }
    },
    coin_8_status = {
        id = "coin_8_status",
        persisted = true,
        default = "locked",
        set_by = {
            "CoinVaultScene"
        },
        read_by = {
            "CoinVaultScene"
        }
    },
    coin_9_status = {
        id = "coin_9_status",
        persisted = true,
        default = "locked",
        set_by = {
            "CoinVaultScene"
        },
        read_by = {
            "CoinVaultScene"
        }
    },
    coin_10_status = {
        id = "coin_10_status",
        persisted = true,
        default = "locked",
        set_by = {
            "CoinVaultScene"
        },
        read_by = {
            "CoinVaultScene"
        }
    },
    coin_11_status = {
        id = "coin_11_status",
        persisted = true,
        default = "locked",
        set_by = {
            "CoinVaultScene"
        },
        read_by = {
            "CoinVaultScene"
        }
    },
    coin_12_status = {
        id = "coin_12_status",
        persisted = true,
        default = "locked",
        set_by = {
            "CoinVaultScene"
        },
        read_by = {
            "CoinVaultScene"
        }
    },
    coin_13_status = {
        id = "coin_13_status",
        persisted = true,
        default = "locked",
        set_by = {
            "CoinVaultScene"
        },
        read_by = {
            "CoinVaultScene"
        }
    },
    coin_14_status = {
        id = "coin_14_status",
        persisted = true,
        default = "locked",
        set_by = {
            "CoinVaultScene"
        },
        read_by = {
            "CoinVaultScene"
        }
    },
    coin_15_status = {
        id = "coin_15_status",
        persisted = true,
        default = "locked",
        set_by = {
            "CoinVaultScene"
        },
        read_by = {
            "CoinVaultScene"
        }
    },
    coin_16_status = {
        id = "coin_16_status",
        persisted = true,
        default = "locked",
        set_by = {
            "CoinVaultScene"
        },
        read_by = {
            "CoinVaultScene"
        }
    },
    coin_17_status = {
        id = "coin_17_status",
        persisted = true,
        default = "locked",
        set_by = {
            "CoinVaultScene"
        },
        read_by = {
            "CoinVaultScene"
        }
    },
    coin_18_status = {
        id = "coin_18_status",
        persisted = true,
        default = "locked",
        set_by = {
            "CoinVaultScene"
        },
        read_by = {
            "CoinVaultScene"
        }
    },
    coin_19_status = {
        id = "coin_19_status",
        persisted = true,
        default = "locked",
        set_by = {
            "CoinVaultScene"
        },
        read_by = {
            "CoinVaultScene"
        }
    },
    coin_20_status = {
        id = "coin_20_status",
        persisted = true,
        default = "locked",
        set_by = {
            "CoinVaultScene"
        },
        read_by = {
            "CoinVaultScene"
        }
    },
    coin_21_status = {
        id = "coin_21_status",
        persisted = true,
        default = "locked",
        set_by = {
            "CoinVaultScene"
        },
        read_by = {
            "CoinVaultScene"
        }
    },
    coin_22_status = {
        id = "coin_22_status",
        persisted = true,
        default = "locked",
        set_by = {
            "CoinVaultScene"
        },
        read_by = {
            "CoinVaultScene"
        }
    },
    coin_23_status = {
        id = "coin_23_status",
        persisted = true,
        default = "locked",
        set_by = {
            "CoinVaultScene"
        },
        read_by = {
            "CoinVaultScene"
        }
    }
}

canon.animation_names = {
    newb_idle_south = {
        id = "newb_idle_south",
        character = "newb",
        sprite_table = "images/newb-table-32-32"
    },
    newb_walk_south = {
        id = "newb_walk_south",
        character = "newb",
        sprite_table = "images/newb-table-32-32"
    },
    newb_idle_north = {
        id = "newb_idle_north",
        character = "newb",
        sprite_table = "images/newb-table-32-32"
    },
    newb_walk_north = {
        id = "newb_walk_north",
        character = "newb",
        sprite_table = "images/newb-table-32-32"
    },
    newb_idle_east = {
        id = "newb_idle_east",
        character = "newb",
        sprite_table = "images/newb-table-32-32"
    },
    newb_walk_east = {
        id = "newb_walk_east",
        character = "newb",
        sprite_table = "images/newb-table-32-32"
    },
    newb_idle_west = {
        id = "newb_idle_west",
        character = "newb",
        sprite_table = "images/newb-table-32-32"
    },
    newb_walk_west = {
        id = "newb_walk_west",
        character = "newb",
        sprite_table = "images/newb-table-32-32"
    },
    newb_interact = {
        id = "newb_interact",
        character = "newb",
        sprite_table = "images/newb-table-32-32"
    },
    newb_surprised = {
        id = "newb_surprised",
        character = "newb",
        sprite_table = "images/newb-table-32-32"
    },
    terminal_typewriter = {
        id = "terminal_typewriter",
        character = "system",
        sprite_table = nil
    },
    lockpick_pin_set = {
        id = "lockpick_pin_set",
        character = "system",
        sprite_table = nil
    },
    tyson_cabinet_attract = {
        id = "tyson_cabinet_attract",
        character = "system",
        sprite_table = nil
    },
    coin_vault_zoom = {
        id = "coin_vault_zoom",
        character = "system",
        sprite_table = nil
    },
    crt_collapse = {
        id = "crt_collapse",
        character = "system",
        sprite_table = nil
    }
}

canon.asset_paths = {
    title = "images/title",
    pwnglove_icon = "images/pwnglove_icon",
    newb_table = "images/newb-table-32-32",
    newb_portrait = "images/portraits/newb",
    lockpick_body = "images/ui/lockpick_body",
    playground_bg = "images/scenes/pwnglove_playground",
    tileset_hakcd = "images/tilesets/hakcd-table-24-24",
    coin_0 = "images/coins/coin_0",
    coin_0_large = "images/coins/coin_0_large",
    coin_1 = "images/coins/coin_1",
    coin_1_large = "images/coins/coin_1_large",
    coin_2 = "images/coins/coin_2",
    coin_2_large = "images/coins/coin_2_large",
    coin_3 = "images/coins/coin_3",
    coin_3_large = "images/coins/coin_3_large",
    coin_locked = "images/coins/coin_locked"
}

canon.sfx_ids = {
    lockpick_pin_click_1 = {
        id = "lockpick_pin_click_1",
        path = "sounds/sfx/lockpick_pin_click_1"
    },
    lockpick_pin_click_2 = {
        id = "lockpick_pin_click_2",
        path = "sounds/sfx/lockpick_pin_click_2"
    },
    lockpick_pin_click_3 = {
        id = "lockpick_pin_click_3",
        path = "sounds/sfx/lockpick_pin_click_3"
    },
    lockpick_pin_click_4 = {
        id = "lockpick_pin_click_4",
        path = "sounds/sfx/lockpick_pin_click_4"
    },
    lockpick_pin_set = {
        id = "lockpick_pin_set",
        path = "sounds/sfx/lockpick_pin_set"
    },
    lockpick_snap = {
        id = "lockpick_snap",
        path = "sounds/sfx/lockpick_snap"
    },
    lockpick_tension_warn = {
        id = "lockpick_tension_warn",
        path = "sounds/sfx/lockpick_tension_warn"
    },
    lockpick_open = {
        id = "lockpick_open",
        path = "sounds/sfx/lockpick_open"
    },
    tyson_digit_select = {
        id = "tyson_digit_select",
        path = "sounds/sfx/tyson_digit_select"
    },
    tyson_digit_commit = {
        id = "tyson_digit_commit",
        path = "sounds/sfx/tyson_digit_commit"
    },
    tyson_winner = {
        id = "tyson_winner",
        path = "sounds/sfx/tyson_winner"
    },
    coin_navigate_tick = {
        id = "coin_navigate_tick",
        path = "sounds/sfx/coin_navigate_tick"
    },
    coin_zoom_whoosh = {
        id = "coin_zoom_whoosh",
        path = "sounds/sfx/coin_zoom_whoosh"
    },
    coin_mint = {
        id = "coin_mint",
        path = "sounds/sfx/coin_mint"
    },
    pwnglove_boot = {
        id = "pwnglove_boot",
        path = "sounds/sfx/pwnglove_boot"
    },
    step_1 = {
        id = "step_1",
        path = "sounds/sfx/step_1"
    },
    step_2 = {
        id = "step_2",
        path = "sounds/sfx/step_2"
    }
}

canon.music_ids = {
    title_loop = {
        id = "title_loop",
        path = "sounds/music/title_loop"
    },
    bedroom_loop = {
        id = "bedroom_loop",
        path = "sounds/music/bedroom_loop"
    },
    playground_loop = {
        id = "playground_loop",
        path = "sounds/music/playground_loop"
    },
    tyson_loop = {
        id = "tyson_loop",
        path = "sounds/music/tyson_loop"
    },
    coinvault_loop = {
        id = "coinvault_loop",
        path = "sounds/music/coinvault_loop"
    }
}

-- Convenience: id-presence assertion. Wraps a canon lookup with a
-- loud error so typos fail at load time, not silently at runtime.
function canon.assert_id(category_name, id)
    local cat = canon[category_name]
    assert(cat, "canon: unknown category '" .. tostring(category_name) .. "'")
    assert(cat[id], "canon: unknown id '" .. tostring(id) .. "' in '" .. category_name .. "'")
    return cat[id]
end

_G.canon = canon
return canon
