-- source/data/continuity.lua
-- GENERATED by tools/canon/generate_continuity.js — do not hand-edit.
-- Re-run after generate_canon.js when story progression changes.
-- Phase 3 of canon-first migration plan.
--
-- Declarative scene order + flag rules + dialogue unlock rules +
-- inventory requirements + puzzle progression + room availability.
-- Phase 7 validator (validate_continuity.sh) reads this + canon.lua
-- to fail build on graph drift.

local continuity = {}

-- Build-scene traversal order (TitleScene -> Bedroom -> modals -> Playground -> minigames)
continuity.scene_order = {
    "TitleScene",
    "BedroomScene",
    "ComputerScene",
    "ModemScene",
    "PhoneScene",
    "PlaygroundScene",
    "LockpickScene",
    "TysonScene",
    "CoinVaultScene"
}

-- Bible story-scene order (SC01..SC26 + coda)
continuity.bible_scene_order = {
    "sc01",
    "sc02",
    "sc03",
    "sc04",
    "sc05",
    "sc06",
    "sc07",
    "sc08",
    "sc09",
    "sc10",
    "sc11",
    "sc12",
    "sc13",
    "sc14",
    "sc15",
    "sc16",
    "sc17",
    "sc18",
    "sc19",
    "sc20",
    "sc21",
    "sc22",
    "sc23",
    "sc24",
    "sc25",
    "sc26"
}

-- Per-scene continuity entries — required/sets flags, characters, objects, transitions
continuity.scenes = {
    {
        id = "TitleScene",
        room = "title",
        required_flags = {},
        sets_flags = {},
        characters = {
            "newb"
        },
        objects = {},
        transitions_to = {
            "BedroomScene"
        }
    },
    {
        id = "BedroomScene",
        room = "sc01",
        required_flags = {},
        sets_flags = {},
        characters = {
            "newb",
            "mom"
        },
        objects = {
            "computer",
            "modem",
            "phone",
            "bed"
        },
        transitions_to = {
            "ComputerScene",
            "ModemScene",
            "PhoneScene",
            "PlaygroundScene"
        }
    },
    {
        id = "ComputerScene",
        room = "sc01",
        parent_scene = "BedroomScene",
        required_flags = {},
        sets_flags = {},
        characters = {
            "newb",
            "mentor"
        },
        objects = {
            "computer"
        },
        transitions_to = {
            "BedroomScene"
        },
        dialogue = {
            "bbs_boot_sequence"
        }
    },
    {
        id = "ModemScene",
        room = "sc01",
        parent_scene = "BedroomScene",
        required_flags = {},
        sets_flags = {},
        characters = {
            "newb"
        },
        objects = {
            "modem"
        },
        transitions_to = {
            "BedroomScene"
        },
        dialogue = {
            "modem_war_dialer"
        }
    },
    {
        id = "PhoneScene",
        room = "sc01",
        parent_scene = "BedroomScene",
        required_flags = {},
        sets_flags = {},
        characters = {
            "newb",
            "mom"
        },
        objects = {
            "phone"
        },
        transitions_to = {
            "BedroomScene"
        },
        dialogue = {
            "mom_intro"
        }
    },
    {
        id = "PlaygroundScene",
        room = "playground",
        required_flags = {},
        sets_flags = {
            "pwnglove_mode_complete"
        },
        characters = {
            "newb"
        },
        objects = {
            "lockpick_station",
            "tyson_cabinet",
            "coin_vault",
            "rfid_pedestal",
            "payphone",
            "ir_wall",
            "gravity_arena",
            "subghz_tuner",
            "portal_pedestal"
        },
        transitions_to = {
            "LockpickScene",
            "TysonScene",
            "CoinVaultScene"
        }
    },
    {
        id = "LockpickScene",
        room = "playground",
        parent_scene = "PlaygroundScene",
        required_flags = {},
        sets_flags = {},
        characters = {
            "newb"
        },
        objects = {
            "lockpick_station"
        },
        transitions_to = {
            "PlaygroundScene"
        }
    },
    {
        id = "TysonScene",
        room = "playground",
        parent_scene = "PlaygroundScene",
        required_flags = {},
        sets_flags = {
            "tyson_unlock"
        },
        characters = {
            "newb"
        },
        objects = {
            "tyson_cabinet"
        },
        transitions_to = {
            "PlaygroundScene"
        },
        dialogue = {
            "tyson_already"
        }
    },
    {
        id = "CoinVaultScene",
        room = "playground",
        parent_scene = "PlaygroundScene",
        required_flags = {},
        sets_flags = {},
        characters = {
            "newb"
        },
        objects = {
            "coin_vault"
        },
        transitions_to = {
            "PlaygroundScene"
        },
        dialogue = {
            "coin_zero_welcome"
        }
    }
}

-- Named flag rules (cross-scene state contracts)
continuity.flag_rules = {
    tyson_persistence = {
        flag = "tyson_unlock",
        rule = "Once set true via TysonScene win, persists across sessions via Noble.GameData. Subsequent TysonScene entries enter already_granted branch."
    },
    coin_mint_progression = {
        flag_prefix = "coin_*_status",
        rule = "Each coin transitions locked -> available -> minted. Available unlock fires when phrase discovered (placeholder until phrase puzzles ship). Coin 0 minted by default."
    },
    pwnglove_mode_completion = {
        flag = "pwnglove_mode_complete",
        rule = "Set true when all 9 playground stations have been A-pressed at least once. Tracked transiently by PlaygroundScene; persisted on first all-9 visit."
    },
    act_progression = {
        flag = "current_act",
        rule = "1..4 (+ Coda). Increments on per-act final scene completion. Currently no scenes advance act — placeholder for Phase 12+ when bible scenes wire in."
    }
}

-- Dialogue unlock rules — when each dialogue id becomes playable
continuity.dialogue_unlock_rules = {
    mom_intro = {
        unlocked_by = "enter_phone_hotspot",
        repeatable = true
    },
    bbs_boot_sequence = {
        unlocked_by = "enter_computer_hotspot",
        repeatable = true
    },
    modem_war_dialer = {
        unlocked_by = "enter_modem_hotspot",
        repeatable = true
    },
    coin_zero_welcome = {
        unlocked_by = "enter_coin_vault_for_first",
        repeatable = false
    },
    tyson_already = {
        unlocked_by = "tyson_unlock_flag_true",
        repeatable = true,
        requires_flag = {
            name = "tyson_unlock",
            value = true
        }
    }
}

-- Per-beat tool/inventory requirements (from bible SKILL GATE MAP)
continuity.inventory_requirements = {
    ["Act 1 b3: Corporate BBS file leech"] = {
        beat = "Act 1 b3: Corporate BBS file leech",
        required_tool = "War Dialer",
        optional_tools = {}
    },
    ["Act 1 b6: Encrypted file from Mentor"] = {
        beat = "Act 1 b6: Encrypted file from Mentor",
        required_tool = "Password Cracker",
        optional_tools = {}
    },
    ["Act 1 b8: Bypass mom's \"off the phone\" demand"] = {
        beat = "Act 1 b8: Bypass mom's \"off the phone\" demand",
        required_tool = "Social Engineering (mom is the first SE target, comedically)",
        optional_tools = {}
    },
    ["Act 2 b1: Install AOL"] = {
        beat = "Act 2 b1: Install AOL",
        required_tool = "none (cutscene)",
        optional_tools = {}
    },
    ["Act 2 b5: Get phractal to vouch"] = {
        beat = "Act 2 b5: Get phractal to vouch",
        required_tool = "Read 3 specific textfiles",
        optional_tools = {}
    },
    ["Act 2 b8: Enter #private_chan_7"] = {
        beat = "Act 2 b8: Enter #private_chan_7",
        required_tool = "Password Cracker",
        optional_tools = {
            "Social Engineering (alternate path)"
        }
    },
    ["Act 3 b1: Call k0nsole from payphone"] = {
        beat = "Act 3 b1: Call k0nsole from payphone",
        required_tool = "Red Box",
        optional_tools = {}
    },
    ["Act 3 b3: Beige box tap on Bell pedestal"] = {
        beat = "Act 3 b3: Beige box tap on Bell pedestal",
        required_tool = "Lockpick + Beige Box",
        optional_tools = {}
    },
    ["Act 3 b5: Switching office"] = {
        beat = "Act 3 b5: Switching office",
        required_tool = "Blue Box",
        optional_tools = {}
    },
    ["Act 3 b7: Aegis tech support"] = {
        beat = "Act 3 b7: Aegis tech support",
        required_tool = "Social Engineering",
        optional_tools = {}
    },
    ["Act 3 b8: Aegis dev VPN"] = {
        beat = "Act 3 b8: Aegis dev VPN",
        required_tool = "Password Cracker (advanced)",
        optional_tools = {}
    },
    ["Act 4 b3: RedHook confrontation"] = {
        beat = "Act 4 b3: RedHook confrontation",
        required_tool = "Social Engineering (last-ditch)",
        optional_tools = {}
    },
    ["Act 4 b5: Encrypt and bury evidence"] = {
        beat = "Act 4 b5: Encrypt and bury evidence",
        required_tool = "War Dialer (entropy mode)",
        optional_tools = {}
    }
}

-- Per-puzzle progression metadata
continuity.puzzle_progression = {
    lockpick = {
        scene = "LockpickScene",
        bible_beat = "Act 3 b3: Beige box tap on Bell pedestal",
        unlock_state = "available_at_act3",
        gating_tool = "Lockpick + Beige Box",
        currently_implemented = true,
        current_invocation_room = "playground"
    },
    tyson_code = {
        scene = "TysonScene",
        bible_beat = "easter egg — pre-canonical",
        unlock_state = "always_available_when_pwnglove_equipped",
        gating_tool = "PWNGLOVE",
        currently_implemented = true,
        current_invocation_room = "playground"
    },
    coin_vault = {
        scene = "CoinVaultScene",
        bible_beat = "collection — per-coin phrase discovery",
        unlock_state = "always_browsable_in_playground",
        gating_tool = "PWNGLOVE",
        currently_implemented = true,
        current_invocation_room = "playground"
    }
}

-- Room availability — when each room is reachable
continuity.room_availability = {
    title = {
        available_when = "always"
    },
    sc01 = {
        available_when = "always (recurring hub)"
    },
    playground = {
        available_when = "always (system menu accessible)"
    },
    sc02 = {
        available_when = "bible scene SC02 (Act 1: The Boards (8 beats, 5 locations)) — not yet implemented in v4 build"
    },
    sc03 = {
        available_when = "bible scene SC03 (Act 1: The Boards (8 beats, 5 locations)) — not yet implemented in v4 build"
    },
    sc04 = {
        available_when = "bible scene SC04 (Act 1: The Boards (8 beats, 5 locations)) — not yet implemented in v4 build"
    },
    sc05 = {
        available_when = "bible scene SC05 (Act 1: The Boards (8 beats, 5 locations)) — not yet implemented in v4 build"
    },
    sc06 = {
        available_when = "bible scene SC06 (Act 2: The Garden (10 beats, 6 locations)) — not yet implemented in v4 build"
    },
    sc07 = {
        available_when = "bible scene SC07 (Act 2: The Garden (10 beats, 6 locations)) — not yet implemented in v4 build"
    },
    sc08 = {
        available_when = "bible scene SC08 (Act 2: The Garden (10 beats, 6 locations)) — not yet implemented in v4 build"
    },
    sc09 = {
        available_when = "bible scene SC09 (Act 2: The Garden (10 beats, 6 locations)) — not yet implemented in v4 build"
    },
    sc10 = {
        available_when = "bible scene SC10 (Act 2: The Garden (10 beats, 6 locations)) — not yet implemented in v4 build"
    },
    sc11 = {
        available_when = "bible scene SC11 (Act 2: The Garden (10 beats, 6 locations)) — not yet implemented in v4 build"
    },
    sc12 = {
        available_when = "bible scene SC12 (Act 2: The Garden (10 beats, 6 locations)) — not yet implemented in v4 build"
    },
    sc13 = {
        available_when = "bible scene SC13 (Act 2: The Garden (10 beats, 6 locations)) — not yet implemented in v4 build"
    },
    sc14 = {
        available_when = "bible scene SC14 (Act 3: The Wires (8 beats, 7 locations)) — not yet implemented in v4 build"
    },
    sc15 = {
        available_when = "bible scene SC15 (Act 3: The Wires (8 beats, 7 locations)) — not yet implemented in v4 build"
    },
    sc16 = {
        available_when = "bible scene SC16 (Act 3: The Wires (8 beats, 7 locations)) — not yet implemented in v4 build"
    },
    sc17 = {
        available_when = "bible scene SC17 (Act 3: The Wires (8 beats, 7 locations)) — not yet implemented in v4 build"
    },
    sc18 = {
        available_when = "bible scene SC18 (Act 3: The Wires (8 beats, 7 locations)) — not yet implemented in v4 build"
    },
    sc19 = {
        available_when = "bible scene SC19 (Act 3: The Wires (8 beats, 7 locations)) — not yet implemented in v4 build"
    },
    sc20 = {
        available_when = "bible scene SC20 (Act 3: The Wires (8 beats, 7 locations)) — not yet implemented in v4 build"
    },
    sc21 = {
        available_when = "bible scene SC21 (Act 4: The Game (6 beats, 4 locations)) — not yet implemented in v4 build"
    },
    sc22 = {
        available_when = "bible scene SC22 (Act 4: The Game (6 beats, 4 locations)) — not yet implemented in v4 build"
    },
    sc23 = {
        available_when = "bible scene SC23 (Act 4: The Game (6 beats, 4 locations)) — not yet implemented in v4 build"
    },
    sc24 = {
        available_when = "bible scene SC24 (Act 4: The Game (6 beats, 4 locations)) — not yet implemented in v4 build"
    },
    sc25 = {
        available_when = "bible scene SC25 (Coda) — not yet implemented in v4 build"
    },
    sc26 = {
        available_when = "bible scene SC26 (Coda) — not yet implemented in v4 build"
    }
}

_G.continuity = continuity
return continuity
