-- source/data/rooms.lua
-- GENERATED by tools/canon/generate_rooms_manifest.js — do not hand-edit.
-- Re-run after generate_canon.js when room shapes / hotspot positions /
-- LDtk levels change.
-- Phase 6 of canon-first migration plan.
--
-- Per-room declarative manifest:
--   id                          — matches canon.rooms[id]
--   bible_name                  — human-readable label from the bible
--   ldtk_level                  — LDtk level identifier (or nil if non-LDtk)
--   is_story_room               — bible canon scene vs sandbox/title
--   not_yet_implemented         — true for bible scenes without v4 build
--   walkable_bounds             — { x, y, w, h } in scene pixel coords (or nil)
--   exits                       — [{ from_object_id, to_scene, to_spawn }]
--   spawn_points                — [{ id, x, y }]
--   interactable_objects        — [canon.objects ids in this room]
--   npcs                        — [canon.characters ids present in room]
--   camera_behavior             — 'static' | 'follow' | 'scroll' (HAKCD: static)
--   ambient_animation_objects   — [canon.animation_names ids that loop]
--   background                  — canon.asset_paths id (or nil if LDtk-tiled)
--
-- Phase 7 validator (validate_rooms.sh) cross-checks every id against
-- canon.lua and warns on not_yet_implemented but does not block.

local rooms = {
    title = {
        id = "title",
        bible_name = "Title Splash",
        ldtk_level = nil,
        is_story_room = false,
        not_yet_implemented = false,
        walkable_bounds = nil,
        exits = {},
        spawn_points = {},
        interactable_objects = {},
        npcs = {},
        camera_behavior = "static",
        ambient_animation_objects = {},
        background = "title"
    },
    sc01 = {
        id = "sc01",
        bible_name = "Bedroom (recurring hub)",
        ldtk_level = "Bedroom",
        is_story_room = true,
        not_yet_implemented = false,
        walkable_bounds = {
            x = 0,
            y = 0,
            w = 408,
            h = 240
        },
        exits = {
            {
                from_object_id = "computer",
                to_scene = "ComputerScene",
                to_spawn = "default"
            },
            {
                from_object_id = "modem",
                to_scene = "ModemScene",
                to_spawn = "default"
            },
            {
                from_object_id = "phone",
                to_scene = "PhoneScene",
                to_spawn = "default"
            },
            {
                from_object_id = "bed",
                to_scene = "PlaygroundScene",
                to_spawn = "default"
            }
        },
        spawn_points = {
            {
                id = "default",
                x = 192,
                y = 168
            }
        },
        interactable_objects = {
            "computer",
            "modem",
            "phone",
            "bed"
        },
        npcs = {
            "mom"
        },
        camera_behavior = "static",
        ambient_animation_objects = {},
        background = nil
    },
    playground = {
        id = "playground",
        bible_name = "PWNGLOVE MODE (sandbox)",
        ldtk_level = "Playground",
        is_story_room = false,
        not_yet_implemented = false,
        walkable_bounds = {
            x = 0,
            y = 0,
            w = 408,
            h = 240
        },
        exits = {
            {
                from_object_id = "lockpick_station",
                to_scene = "LockpickScene",
                to_spawn = "default"
            },
            {
                from_object_id = "tyson_cabinet",
                to_scene = "TysonScene",
                to_spawn = "default"
            },
            {
                from_object_id = "coin_vault",
                to_scene = "CoinVaultScene",
                to_spawn = "default"
            }
        },
        spawn_points = {
            {
                id = "default",
                x = 192,
                y = 168
            }
        },
        interactable_objects = {
            "lockpick_station",
            "tyson_cabinet",
            "coin_vault",
            "rfid_pedestal",
            "payphone",
            "ir_wall",
            "gravity_arena",
            "subghz_tuner",
            "portal_pedestal"
        },
        npcs = {},
        camera_behavior = "static",
        ambient_animation_objects = {},
        background = nil
    },
    sc02 = {
        id = "sc02",
        bible_name = "DEADLINE BBS",
        ldtk_level = nil,
        is_story_room = true,
        not_yet_implemented = true,
        walkable_bounds = nil,
        exits = {},
        spawn_points = {},
        interactable_objects = {},
        npcs = {},
        camera_behavior = "static",
        ambient_animation_objects = {},
        background = nil,
        act = "Act 1: The Boards (8 beats, 5 locations)"
    },
    sc03 = {
        id = "sc03",
        bible_name = "War dialer interface",
        ldtk_level = nil,
        is_story_room = true,
        not_yet_implemented = true,
        walkable_bounds = nil,
        exits = {},
        spawn_points = {},
        interactable_objects = {},
        npcs = {},
        camera_behavior = "static",
        ambient_animation_objects = {},
        background = nil,
        act = "Act 1: The Boards (8 beats, 5 locations)"
    },
    sc04 = {
        id = "sc04",
        bible_name = "Corporate BBS (PhoenixDown)",
        ldtk_level = nil,
        is_story_room = true,
        not_yet_implemented = true,
        walkable_bounds = nil,
        exits = {},
        spawn_points = {},
        interactable_objects = {},
        npcs = {},
        camera_behavior = "static",
        ambient_animation_objects = {},
        background = nil,
        act = "Act 1: The Boards (8 beats, 5 locations)"
    },
    sc05 = {
        id = "sc05",
        bible_name = "The phone bill cutscene",
        ldtk_level = nil,
        is_story_room = true,
        not_yet_implemented = true,
        walkable_bounds = nil,
        exits = {},
        spawn_points = {},
        interactable_objects = {},
        npcs = {},
        camera_behavior = "static",
        ambient_animation_objects = {},
        background = nil,
        act = "Act 1: The Boards (8 beats, 5 locations)"
    },
    sc06 = {
        id = "sc06",
        bible_name = "AOL signup cutscene",
        ldtk_level = nil,
        is_story_room = true,
        not_yet_implemented = true,
        walkable_bounds = nil,
        exits = {},
        spawn_points = {},
        interactable_objects = {},
        npcs = {},
        camera_behavior = "static",
        ambient_animation_objects = {},
        background = nil,
        act = "Act 2: The Garden (10 beats, 6 locations)"
    },
    sc07 = {
        id = "sc07",
        bible_name = "AOL Buddy List / Mail / Chat hub",
        ldtk_level = nil,
        is_story_room = true,
        not_yet_implemented = true,
        walkable_bounds = nil,
        exits = {},
        spawn_points = {},
        interactable_objects = {},
        npcs = {},
        camera_behavior = "static",
        ambient_animation_objects = {},
        background = nil,
        act = "Act 2: The Garden (10 beats, 6 locations)"
    },
    sc08 = {
        id = "sc08",
        bible_name = "#warez_lobby",
        ldtk_level = nil,
        is_story_room = true,
        not_yet_implemented = true,
        walkable_bounds = nil,
        exits = {},
        spawn_points = {},
        interactable_objects = {},
        npcs = {},
        camera_behavior = "static",
        ambient_animation_objects = {},
        background = nil,
        act = "Act 2: The Garden (10 beats, 6 locations)"
    },
    sc09 = {
        id = "sc09",
        bible_name = "#cyber_lounge",
        ldtk_level = nil,
        is_story_room = true,
        not_yet_implemented = true,
        walkable_bounds = nil,
        exits = {},
        spawn_points = {},
        interactable_objects = {},
        npcs = {},
        camera_behavior = "static",
        ambient_animation_objects = {},
        background = nil,
        act = "Act 2: The Garden (10 beats, 6 locations)"
    },
    sc10 = {
        id = "sc10",
        bible_name = "#phreak_kingdom",
        ldtk_level = nil,
        is_story_room = true,
        not_yet_implemented = true,
        walkable_bounds = nil,
        exits = {},
        spawn_points = {},
        interactable_objects = {},
        npcs = {},
        camera_behavior = "static",
        ambient_animation_objects = {},
        background = nil,
        act = "Act 2: The Garden (10 beats, 6 locations)"
    },
    sc11 = {
        id = "sc11",
        bible_name = "#h_p_v_a_c",
        ldtk_level = nil,
        is_story_room = true,
        not_yet_implemented = true,
        walkable_bounds = nil,
        exits = {},
        spawn_points = {},
        interactable_objects = {},
        npcs = {},
        camera_behavior = "static",
        ambient_animation_objects = {},
        background = nil,
        act = "Act 2: The Garden (10 beats, 6 locations)"
    },
    sc12 = {
        id = "sc12",
        bible_name = "#private_chan_7",
        ldtk_level = nil,
        is_story_room = true,
        not_yet_implemented = true,
        walkable_bounds = nil,
        exits = {},
        spawn_points = {},
        interactable_objects = {},
        npcs = {},
        camera_behavior = "static",
        ambient_animation_objects = {},
        background = nil,
        act = "Act 2: The Garden (10 beats, 6 locations)"
    },
    sc13 = {
        id = "sc13",
        bible_name = "ICQ window (overlay)",
        ldtk_level = nil,
        is_story_room = true,
        not_yet_implemented = true,
        walkable_bounds = nil,
        exits = {},
        spawn_points = {},
        interactable_objects = {},
        npcs = {},
        camera_behavior = "static",
        ambient_animation_objects = {},
        background = nil,
        act = "Act 2: The Garden (10 beats, 6 locations)"
    },
    sc14 = {
        id = "sc14",
        bible_name = "Bedroom (return)",
        ldtk_level = nil,
        is_story_room = true,
        not_yet_implemented = true,
        walkable_bounds = nil,
        exits = {},
        spawn_points = {},
        interactable_objects = {},
        npcs = {},
        camera_behavior = "static",
        ambient_animation_objects = {},
        background = nil,
        act = "Act 3: The Wires (8 beats, 7 locations)"
    },
    sc15 = {
        id = "sc15",
        bible_name = "Greyhound station payphone bank",
        ldtk_level = nil,
        is_story_room = true,
        not_yet_implemented = true,
        walkable_bounds = nil,
        exits = {},
        spawn_points = {},
        interactable_objects = {},
        npcs = {},
        camera_behavior = "static",
        ambient_animation_objects = {},
        background = nil,
        act = "Act 3: The Wires (8 beats, 7 locations)"
    },
    sc16 = {
        id = "sc16",
        bible_name = "k0nsole conversation",
        ldtk_level = nil,
        is_story_room = true,
        not_yet_implemented = true,
        walkable_bounds = nil,
        exits = {},
        spawn_points = {},
        interactable_objects = {},
        npcs = {},
        camera_behavior = "static",
        ambient_animation_objects = {},
        background = nil,
        act = "Act 3: The Wires (8 beats, 7 locations)"
    },
    sc17 = {
        id = "sc17",
        bible_name = "Bell pedestal in suburban yard, 2am",
        ldtk_level = nil,
        is_story_room = true,
        not_yet_implemented = true,
        walkable_bounds = nil,
        exits = {},
        spawn_points = {},
        interactable_objects = {},
        npcs = {},
        camera_behavior = "static",
        ambient_animation_objects = {},
        background = nil,
        act = "Act 3: The Wires (8 beats, 7 locations)"
    },
    sc18 = {
        id = "sc18",
        bible_name = "Telco switching office service entrance",
        ldtk_level = nil,
        is_story_room = true,
        not_yet_implemented = true,
        walkable_bounds = nil,
        exits = {},
        spawn_points = {},
        interactable_objects = {},
        npcs = {},
        camera_behavior = "static",
        ambient_animation_objects = {},
        background = nil,
        act = "Act 3: The Wires (8 beats, 7 locations)"
    },
    sc19 = {
        id = "sc19",
        bible_name = "Aegis network reconnaissance",
        ldtk_level = nil,
        is_story_room = true,
        not_yet_implemented = true,
        walkable_bounds = nil,
        exits = {},
        spawn_points = {},
        interactable_objects = {},
        npcs = {},
        camera_behavior = "static",
        ambient_animation_objects = {},
        background = nil,
        act = "Act 3: The Wires (8 beats, 7 locations)"
    },
    sc20 = {
        id = "sc20",
        bible_name = "Aegis tech support phone call",
        ldtk_level = nil,
        is_story_room = true,
        not_yet_implemented = true,
        walkable_bounds = nil,
        exits = {},
        spawn_points = {},
        interactable_objects = {},
        npcs = {},
        camera_behavior = "static",
        ambient_animation_objects = {},
        background = nil,
        act = "Act 3: The Wires (8 beats, 7 locations)"
    },
    sc21 = {
        id = "sc21",
        bible_name = "Inside the Aegis dev network",
        ldtk_level = nil,
        is_story_room = true,
        not_yet_implemented = true,
        walkable_bounds = nil,
        exits = {},
        spawn_points = {},
        interactable_objects = {},
        npcs = {},
        camera_behavior = "static",
        ambient_animation_objects = {},
        background = nil,
        act = "Act 4: The Game (6 beats, 4 locations)"
    },
    sc22 = {
        id = "sc22",
        bible_name = "RedHook's chatroom",
        ldtk_level = nil,
        is_story_room = true,
        not_yet_implemented = true,
        walkable_bounds = nil,
        exits = {},
        spawn_points = {},
        interactable_objects = {},
        npcs = {},
        camera_behavior = "static",
        ambient_animation_objects = {},
        background = nil,
        act = "Act 4: The Game (6 beats, 4 locations)"
    },
    sc23 = {
        id = "sc23",
        bible_name = "Release decision scene",
        ldtk_level = nil,
        is_story_room = true,
        not_yet_implemented = true,
        walkable_bounds = nil,
        exits = {},
        spawn_points = {},
        interactable_objects = {},
        npcs = {},
        camera_behavior = "static",
        ambient_animation_objects = {},
        background = nil,
        act = "Act 4: The Game (6 beats, 4 locations)"
    },
    sc24 = {
        id = "sc24",
        bible_name = "Exfiltration",
        ldtk_level = nil,
        is_story_room = true,
        not_yet_implemented = true,
        walkable_bounds = nil,
        exits = {},
        spawn_points = {},
        interactable_objects = {},
        npcs = {},
        camera_behavior = "static",
        ambient_animation_objects = {},
        background = nil,
        act = "Act 4: The Game (6 beats, 4 locations)"
    },
    sc25 = {
        id = "sc25",
        bible_name = "2002. Older protagonist's apartment",
        ldtk_level = nil,
        is_story_room = true,
        not_yet_implemented = true,
        walkable_bounds = nil,
        exits = {},
        spawn_points = {},
        interactable_objects = {},
        npcs = {},
        camera_behavior = "static",
        ambient_animation_objects = {},
        background = nil,
        act = "Coda"
    },
    sc26 = {
        id = "sc26",
        bible_name = "SecKC at Knuckleheads (post-credits coda)",
        ldtk_level = nil,
        is_story_room = true,
        not_yet_implemented = true,
        walkable_bounds = nil,
        exits = {},
        spawn_points = {},
        interactable_objects = {},
        npcs = {},
        camera_behavior = "static",
        ambient_animation_objects = {},
        background = nil,
        act = "Coda"
    }
}

_G.rooms_manifest = rooms
return rooms
