-- source/data/visual_spec.lua
-- GENERATED by tools/canon/generate_visual_spec.js — do not hand-edit.
-- Re-run whenever an asset is added/removed/reclassified.
-- Phase V2 of visual recovery plan (see docs/VISUAL_PIPELINE_FAILURE_AUDIT.md §13).
--
-- This is the VISUAL CONTRACT. Phase V3 validator will enforce it. Every
-- shippable asset declares its art_status, human_reviewed sign-off,
-- target_dimensions, readability floor, reference image, and audit notes.
--
-- Status values:
--   'final'       — authored, human-reviewed, ships canonically.
--   'placeholder' — known-bad asset awaiting V4-V8 replacement.
--   'generated'   — synthesized (sfx) or scraped (music); acceptable to ship.
--   'wip'         — in active development, not ship-ready.
--   'debug'       — engine fixtures, dev-only; should not appear in release.
--
-- Reference: docs/style_guide.md §2 (character scale), §9 (hardware
-- readability), §12 (sign-off). All readability floors trace back to
-- "player sprite must occupy >= 15% of vertical screen at 400x240".

local visual_spec = {
    background1 = {
        art_status = "debug",
        frame_count = 1,
        human_reviewed = false,
        id = "background1",
        meets_readability_min = true,
        notes = "Noble engine demo background fixture; not referenced by HAKCD scenes. Ships only because pdc bundles source/assets/images/. Candidate for removal.",
        path = "assets/images/background1",
        readability_min_pct_screen = 0,
        reference_image = nil,
        reviewed_at = nil,
        reviewer = nil,
        sheet_dimensions = {
            h = 240,
            w = 400
        },
        target_dimensions = {
            h = 240,
            w = 400
        },
        target_replacement_version = nil,
        type = "image"
    },
    background2 = {
        art_status = "debug",
        frame_count = 1,
        human_reviewed = false,
        id = "background2",
        meets_readability_min = true,
        notes = "Noble engine demo background fixture; not referenced by HAKCD scenes. Ships only because pdc bundles source/assets/images/. Candidate for removal.",
        path = "assets/images/background2",
        readability_min_pct_screen = 0,
        reference_image = nil,
        reviewed_at = nil,
        reviewer = nil,
        sheet_dimensions = {
            h = 240,
            w = 400
        },
        target_dimensions = {
            h = 240,
            w = 400
        },
        target_replacement_version = nil,
        type = "image"
    },
    bedroom_loop = {
        art_status = "generated",
        duration_bytes = 15876250,
        frame_count = nil,
        human_reviewed = false,
        id = "bedroom_loop",
        meets_readability_min = true,
        notes = "Keygen-scraper sourced, normalized to keygen_loudness_baseline.txt. Not pro-mastered. Acceptable for ship; replace if pro audio pass scheduled.",
        path = "sounds/music/bedroom_loop",
        readability_min_pct_screen = 0,
        reference_image = nil,
        reviewed_at = nil,
        reviewer = nil,
        sheet_dimensions = nil,
        target_dimensions = nil,
        target_replacement_version = nil,
        type = "music"
    },
    coin_0 = {
        art_status = "final",
        frame_count = 1,
        human_reviewed = true,
        id = "coin_0",
        meets_readability_min = true,
        notes = "Canonical pin from real 23-codes/23Coins repo coin art.",
        path = "images/coins/coin_0",
        readability_min_pct_screen = 0.13,
        reference_image = nil,
        reviewed_at = "2026-05-23",
        reviewer = "cory_k",
        sheet_dimensions = {
            h = 48,
            w = 48
        },
        target_dimensions = {
            h = 48,
            w = 48
        },
        target_replacement_version = nil,
        type = "image"
    },
    coin_0_large = {
        art_status = "final",
        frame_count = 1,
        human_reviewed = true,
        id = "coin_0_large",
        meets_readability_min = true,
        notes = "Canonical pin (zoom variant) from real 23-codes/23Coins repo coin art.",
        path = "images/coins/coin_0_large",
        readability_min_pct_screen = 0.5,
        reference_image = nil,
        reviewed_at = "2026-05-23",
        reviewer = "cory_k",
        sheet_dimensions = {
            h = 200,
            w = 200
        },
        target_dimensions = {
            h = 200,
            w = 200
        },
        target_replacement_version = nil,
        type = "image"
    },
    coin_1 = {
        art_status = "final",
        frame_count = 1,
        human_reviewed = true,
        id = "coin_1",
        meets_readability_min = true,
        notes = "Canonical pin from real 23-codes/23Coins repo coin art.",
        path = "images/coins/coin_1",
        readability_min_pct_screen = 0.13,
        reference_image = nil,
        reviewed_at = "2026-05-23",
        reviewer = "cory_k",
        sheet_dimensions = {
            h = 48,
            w = 48
        },
        target_dimensions = {
            h = 48,
            w = 48
        },
        target_replacement_version = nil,
        type = "image"
    },
    coin_1_large = {
        art_status = "final",
        frame_count = 1,
        human_reviewed = true,
        id = "coin_1_large",
        meets_readability_min = true,
        notes = "Canonical pin (zoom variant) from real 23-codes/23Coins repo coin art.",
        path = "images/coins/coin_1_large",
        readability_min_pct_screen = 0.5,
        reference_image = nil,
        reviewed_at = "2026-05-23",
        reviewer = "cory_k",
        sheet_dimensions = {
            h = 200,
            w = 200
        },
        target_dimensions = {
            h = 200,
            w = 200
        },
        target_replacement_version = nil,
        type = "image"
    },
    coin_2 = {
        art_status = "final",
        frame_count = 1,
        human_reviewed = true,
        id = "coin_2",
        meets_readability_min = true,
        notes = "Canonical pin from real 23-codes/23Coins repo coin art.",
        path = "images/coins/coin_2",
        readability_min_pct_screen = 0.13,
        reference_image = nil,
        reviewed_at = "2026-05-23",
        reviewer = "cory_k",
        sheet_dimensions = {
            h = 48,
            w = 48
        },
        target_dimensions = {
            h = 48,
            w = 48
        },
        target_replacement_version = nil,
        type = "image"
    },
    coin_2_large = {
        art_status = "final",
        frame_count = 1,
        human_reviewed = true,
        id = "coin_2_large",
        meets_readability_min = true,
        notes = "Canonical pin (zoom variant) from real 23-codes/23Coins repo coin art.",
        path = "images/coins/coin_2_large",
        readability_min_pct_screen = 0.5,
        reference_image = nil,
        reviewed_at = "2026-05-23",
        reviewer = "cory_k",
        sheet_dimensions = {
            h = 200,
            w = 200
        },
        target_dimensions = {
            h = 200,
            w = 200
        },
        target_replacement_version = nil,
        type = "image"
    },
    coin_3 = {
        art_status = "final",
        frame_count = 1,
        human_reviewed = true,
        id = "coin_3",
        meets_readability_min = true,
        notes = "Canonical pin from real 23-codes/23Coins repo coin art.",
        path = "images/coins/coin_3",
        readability_min_pct_screen = 0.13,
        reference_image = nil,
        reviewed_at = "2026-05-23",
        reviewer = "cory_k",
        sheet_dimensions = {
            h = 48,
            w = 48
        },
        target_dimensions = {
            h = 48,
            w = 48
        },
        target_replacement_version = nil,
        type = "image"
    },
    coin_3_large = {
        art_status = "final",
        frame_count = 1,
        human_reviewed = true,
        id = "coin_3_large",
        meets_readability_min = true,
        notes = "Canonical pin (zoom variant) from real 23-codes/23Coins repo coin art.",
        path = "images/coins/coin_3_large",
        readability_min_pct_screen = 0.5,
        reference_image = nil,
        reviewed_at = "2026-05-23",
        reviewer = "cory_k",
        sheet_dimensions = {
            h = 200,
            w = 200
        },
        target_dimensions = {
            h = 200,
            w = 200
        },
        target_replacement_version = nil,
        type = "image"
    },
    coin_locked = {
        art_status = "final",
        frame_count = 1,
        human_reviewed = true,
        id = "coin_locked",
        meets_readability_min = true,
        notes = "Authored via 23Studios visual_pack_factory v3.1 (OpenRouter gemini-2.5-flash-image, 1-bit postprocessed). Locked-coin glyph with padlock + dotted rim.",
        path = "images/coins/coin_locked",
        readability_min_pct_screen = 0.13,
        reference_image = "docs/reference/ui/coin_vault/coin_locked.md",
        reviewed_at = "2026-05-26",
        reviewer = "cory",
        sheet_dimensions = {
            h = 48,
            w = 48
        },
        target_dimensions = {
            h = 48,
            w = 48
        },
        target_replacement_version = "v0.1.33",
        type = "image"
    },
    coin_mint = {
        art_status = "generated",
        duration_bytes = 15512,
        frame_count = nil,
        human_reviewed = false,
        id = "coin_mint",
        meets_readability_min = true,
        notes = "Synthesized via tools/audio/sfx_synth.js / synth_v4_sfx.js. Normalized but not pro-mastered. Acceptable for ship; replace if pro audio pass scheduled.",
        path = "sounds/sfx/coin_mint",
        readability_min_pct_screen = 0,
        reference_image = nil,
        reviewed_at = nil,
        reviewer = nil,
        sheet_dimensions = nil,
        target_dimensions = nil,
        target_replacement_version = nil,
        type = "sfx"
    },
    coin_navigate_tick = {
        art_status = "generated",
        duration_bytes = 1048,
        frame_count = nil,
        human_reviewed = false,
        id = "coin_navigate_tick",
        meets_readability_min = true,
        notes = "Synthesized via tools/audio/sfx_synth.js / synth_v4_sfx.js. Normalized but not pro-mastered. Acceptable for ship; replace if pro audio pass scheduled.",
        path = "sounds/sfx/coin_navigate_tick",
        readability_min_pct_screen = 0,
        reference_image = nil,
        reviewed_at = nil,
        reviewer = nil,
        sheet_dimensions = nil,
        target_dimensions = nil,
        target_replacement_version = nil,
        type = "sfx"
    },
    coin_zoom_whoosh = {
        art_status = "generated",
        duration_bytes = 9780,
        frame_count = nil,
        human_reviewed = false,
        id = "coin_zoom_whoosh",
        meets_readability_min = true,
        notes = "Synthesized via tools/audio/sfx_synth.js / synth_v4_sfx.js. Normalized but not pro-mastered. Acceptable for ship; replace if pro audio pass scheduled.",
        path = "sounds/sfx/coin_zoom_whoosh",
        readability_min_pct_screen = 0,
        reference_image = nil,
        reviewed_at = nil,
        reviewer = nil,
        sheet_dimensions = nil,
        target_dimensions = nil,
        target_replacement_version = nil,
        type = "sfx"
    },
    coinvault_loop = {
        art_status = "generated",
        duration_bytes = 11834728,
        frame_count = nil,
        human_reviewed = false,
        id = "coinvault_loop",
        meets_readability_min = true,
        notes = "Keygen-scraper sourced, normalized to keygen_loudness_baseline.txt. Not pro-mastered. Acceptable for ship; replace if pro audio pass scheduled.",
        path = "sounds/music/coinvault_loop",
        readability_min_pct_screen = 0,
        reference_image = nil,
        reviewed_at = nil,
        reviewer = nil,
        sheet_dimensions = nil,
        target_dimensions = nil,
        target_replacement_version = nil,
        type = "music"
    },
    hakcd_table_24_24 = {
        art_status = "final",
        frame_count = 64,
        human_reviewed = true,
        id = "hakcd_table_24_24",
        meets_readability_min = true,
        notes = "Authored via 23Studios visual_pack_factory v3.1 (OpenRouter gemini-2.5-flash-image). 8x8 grid of 24x24 1-bit tiles for the bedroom + arcade scenes.",
        path = "images/tilesets/hakcd-table-24-24",
        readability_min_pct_screen = 0,
        reference_image = "docs/reference/rooms/bedroom/tileset_24_24.md",
        reviewed_at = "2026-05-26",
        reviewer = "cory",
        sheet_dimensions = {
            h = 192,
            w = 192
        },
        target_dimensions = {
            h = 24,
            w = 24
        },
        target_replacement_version = "v0.1.34",
        type = "tileset"
    },
    icon = {
        art_status = "final",
        frame_count = 1,
        human_reviewed = true,
        id = "icon",
        meets_readability_min = true,
        notes = "System-menu icon derived from canonical title art.",
        path = "icon",
        readability_min_pct_screen = 0,
        reference_image = "docs/hakcd_title.png",
        reviewed_at = "2026-05-23",
        reviewer = "cory_k",
        sheet_dimensions = {
            h = 32,
            w = 32
        },
        target_dimensions = {
            h = 32,
            w = 32
        },
        target_replacement_version = nil,
        type = "image"
    },
    launcher_card = {
        art_status = "final",
        frame_count = 1,
        human_reviewed = true,
        id = "launcher_card",
        meets_readability_min = true,
        notes = "Launcher card derived from canonical title art.",
        path = "assets/launcher/card",
        readability_min_pct_screen = 0,
        reference_image = "docs/hakcd_title.png",
        reviewed_at = "2026-05-23",
        reviewer = "cory_k",
        sheet_dimensions = {
            h = 155,
            w = 350
        },
        target_dimensions = {
            h = 155,
            w = 350
        },
        target_replacement_version = nil,
        type = "image"
    },
    launcher_card_pressed = {
        art_status = "final",
        frame_count = 1,
        human_reviewed = true,
        id = "launcher_card_pressed",
        meets_readability_min = true,
        notes = "Launcher card pressed-state derived from canonical title art.",
        path = "assets/launcher/card-pressed",
        readability_min_pct_screen = 0,
        reference_image = "docs/hakcd_title.png",
        reviewed_at = "2026-05-23",
        reviewer = "cory_k",
        sheet_dimensions = {
            h = 155,
            w = 350
        },
        target_dimensions = {
            h = 155,
            w = 350
        },
        target_replacement_version = nil,
        type = "image"
    },
    launcher_launchImage = {
        art_status = "final",
        frame_count = 1,
        human_reviewed = true,
        id = "launcher_launchImage",
        meets_readability_min = true,
        notes = "Launcher splash derived from canonical title art.",
        path = "assets/launcher/launchImage",
        readability_min_pct_screen = 1,
        reference_image = "docs/hakcd_title.png",
        reviewed_at = "2026-05-23",
        reviewer = "cory_k",
        sheet_dimensions = {
            h = 240,
            w = 400
        },
        target_dimensions = {
            h = 240,
            w = 400
        },
        target_replacement_version = nil,
        type = "image"
    },
    launcher_sound = {
        art_status = "generated",
        duration_bytes = 161348,
        frame_count = nil,
        human_reviewed = false,
        id = "launcher_sound",
        meets_readability_min = true,
        notes = "Synthesized via tools/audio/sfx_synth.js / synth_v4_sfx.js. Normalized but not pro-mastered. Acceptable for ship; replace if pro audio pass scheduled.",
        path = "assets/launcher/sound",
        readability_min_pct_screen = 0,
        reference_image = nil,
        reviewed_at = nil,
        reviewer = nil,
        sheet_dimensions = nil,
        target_dimensions = nil,
        target_replacement_version = nil,
        type = "sfx"
    },
    lockpick_body = {
        art_status = "final",
        frame_count = 1,
        human_reviewed = true,
        id = "lockpick_body",
        meets_readability_min = true,
        notes = "Authored via 23Studios visual_pack_factory v3.1 (OpenRouter gemini-2.5-flash-image). Cylinder-lock UI per Lucas Pope reference, pure 1-bit.",
        path = "images/ui/lockpick_body",
        readability_min_pct_screen = 0.3,
        reference_image = "docs/reference/ui/lockpick/lockpick_pope_ref.md",
        reviewed_at = "2026-05-26",
        reviewer = "cory",
        sheet_dimensions = {
            h = 100,
            w = 240
        },
        target_dimensions = {
            h = 100,
            w = 240
        },
        target_replacement_version = "v0.1.35",
        type = "image"
    },
    lockpick_open = {
        art_status = "generated",
        duration_bytes = 22126,
        frame_count = nil,
        human_reviewed = false,
        id = "lockpick_open",
        meets_readability_min = true,
        notes = "Synthesized via tools/audio/sfx_synth.js / synth_v4_sfx.js. Normalized but not pro-mastered. Acceptable for ship; replace if pro audio pass scheduled.",
        path = "sounds/sfx/lockpick_open",
        readability_min_pct_screen = 0,
        reference_image = nil,
        reviewed_at = nil,
        reviewer = nil,
        sheet_dimensions = nil,
        target_dimensions = nil,
        target_replacement_version = nil,
        type = "sfx"
    },
    lockpick_pin_click_1 = {
        art_status = "generated",
        duration_bytes = 1400,
        frame_count = nil,
        human_reviewed = false,
        id = "lockpick_pin_click_1",
        meets_readability_min = true,
        notes = "Synthesized via tools/audio/sfx_synth.js / synth_v4_sfx.js. Normalized but not pro-mastered. Acceptable for ship; replace if pro audio pass scheduled.",
        path = "sounds/sfx/lockpick_pin_click_1",
        readability_min_pct_screen = 0,
        reference_image = nil,
        reviewed_at = nil,
        reviewer = nil,
        sheet_dimensions = nil,
        target_dimensions = nil,
        target_replacement_version = nil,
        type = "sfx"
    },
    lockpick_pin_click_2 = {
        art_status = "generated",
        duration_bytes = 1400,
        frame_count = nil,
        human_reviewed = false,
        id = "lockpick_pin_click_2",
        meets_readability_min = true,
        notes = "Synthesized via tools/audio/sfx_synth.js / synth_v4_sfx.js. Normalized but not pro-mastered. Acceptable for ship; replace if pro audio pass scheduled.",
        path = "sounds/sfx/lockpick_pin_click_2",
        readability_min_pct_screen = 0,
        reference_image = nil,
        reviewed_at = nil,
        reviewer = nil,
        sheet_dimensions = nil,
        target_dimensions = nil,
        target_replacement_version = nil,
        type = "sfx"
    },
    lockpick_pin_click_3 = {
        art_status = "generated",
        duration_bytes = 1400,
        frame_count = nil,
        human_reviewed = false,
        id = "lockpick_pin_click_3",
        meets_readability_min = true,
        notes = "Synthesized via tools/audio/sfx_synth.js / synth_v4_sfx.js. Normalized but not pro-mastered. Acceptable for ship; replace if pro audio pass scheduled.",
        path = "sounds/sfx/lockpick_pin_click_3",
        readability_min_pct_screen = 0,
        reference_image = nil,
        reviewed_at = nil,
        reviewer = nil,
        sheet_dimensions = nil,
        target_dimensions = nil,
        target_replacement_version = nil,
        type = "sfx"
    },
    lockpick_pin_click_4 = {
        art_status = "generated",
        duration_bytes = 1400,
        frame_count = nil,
        human_reviewed = false,
        id = "lockpick_pin_click_4",
        meets_readability_min = true,
        notes = "Synthesized via tools/audio/sfx_synth.js / synth_v4_sfx.js. Normalized but not pro-mastered. Acceptable for ship; replace if pro audio pass scheduled.",
        path = "sounds/sfx/lockpick_pin_click_4",
        readability_min_pct_screen = 0,
        reference_image = nil,
        reviewed_at = nil,
        reviewer = nil,
        sheet_dimensions = nil,
        target_dimensions = nil,
        target_replacement_version = nil,
        type = "sfx"
    },
    lockpick_pin_set = {
        art_status = "generated",
        duration_bytes = 4488,
        frame_count = nil,
        human_reviewed = false,
        id = "lockpick_pin_set",
        meets_readability_min = true,
        notes = "Synthesized via tools/audio/sfx_synth.js / synth_v4_sfx.js. Normalized but not pro-mastered. Acceptable for ship; replace if pro audio pass scheduled.",
        path = "sounds/sfx/lockpick_pin_set",
        readability_min_pct_screen = 0,
        reference_image = nil,
        reviewed_at = nil,
        reviewer = nil,
        sheet_dimensions = nil,
        target_dimensions = nil,
        target_replacement_version = nil,
        type = "sfx"
    },
    lockpick_snap = {
        art_status = "generated",
        duration_bytes = 11102,
        frame_count = nil,
        human_reviewed = false,
        id = "lockpick_snap",
        meets_readability_min = true,
        notes = "Synthesized via tools/audio/sfx_synth.js / synth_v4_sfx.js. Normalized but not pro-mastered. Acceptable for ship; replace if pro audio pass scheduled.",
        path = "sounds/sfx/lockpick_snap",
        readability_min_pct_screen = 0,
        reference_image = nil,
        reviewed_at = nil,
        reviewer = nil,
        sheet_dimensions = nil,
        target_dimensions = nil,
        target_replacement_version = nil,
        type = "sfx"
    },
    lockpick_tension_warn = {
        art_status = "generated",
        duration_bytes = 17718,
        frame_count = nil,
        human_reviewed = false,
        id = "lockpick_tension_warn",
        meets_readability_min = true,
        notes = "Synthesized via tools/audio/sfx_synth.js / synth_v4_sfx.js. Normalized but not pro-mastered. Acceptable for ship; replace if pro audio pass scheduled.",
        path = "sounds/sfx/lockpick_tension_warn",
        readability_min_pct_screen = 0,
        reference_image = nil,
        reviewed_at = nil,
        reviewer = nil,
        sheet_dimensions = nil,
        target_dimensions = nil,
        target_replacement_version = nil,
        type = "sfx"
    },
    newb = {
        art_status = "final",
        frame_count = 1,
        human_reviewed = true,
        id = "newb",
        meets_readability_min = true,
        notes = "Authored via 23Studios visual_pack_factory v3.1 (OpenRouter gemini-3-pro-image-preview, centred crop + downscale). Cowlick + hoodie + slight smirk, three-quarter view.",
        path = "images/portraits/newb",
        readability_min_pct_screen = 0.2,
        reference_image = "docs/reference/characters/newb/newb_portrait.md",
        reviewed_at = "2026-05-26",
        reviewer = "cory",
        sheet_dimensions = {
            h = 56,
            w = 48
        },
        target_dimensions = {
            h = 56,
            w = 48
        },
        target_replacement_version = "v0.1.33",
        type = "image"
    },
    newb_table_32_32 = {
        art_status = "final",
        frame_count = 28,
        human_reviewed = true,
        id = "newb_table_32_32",
        meets_readability_min = true,
        notes = "Authored via 23Studios visual_pack_factory v3.1 (OpenRouter gemini-2.5-flash-image). 8-frame side-view walk cycle strip, 32x32 per frame.",
        path = "images/newb-table-32-32",
        readability_min_pct_screen = 0.15,
        reference_image = "docs/reference/characters/newb/newb_idle_south.md",
        reviewed_at = "2026-05-26",
        reviewer = "cory",
        sheet_dimensions = {
            h = 224,
            w = 128
        },
        target_dimensions = {
            h = 32,
            w = 32
        },
        target_replacement_version = "v0.1.33",
        type = "imagetable"
    },
    playground_loop = {
        art_status = "generated",
        duration_bytes = 15802270,
        frame_count = nil,
        human_reviewed = false,
        id = "playground_loop",
        meets_readability_min = true,
        notes = "Keygen-scraper sourced, normalized to keygen_loudness_baseline.txt. Not pro-mastered. Acceptable for ship; replace if pro audio pass scheduled.",
        path = "sounds/music/playground_loop",
        readability_min_pct_screen = 0,
        reference_image = nil,
        reviewed_at = nil,
        reviewer = nil,
        sheet_dimensions = nil,
        target_dimensions = nil,
        target_replacement_version = nil,
        type = "music"
    },
    pwnglove_boot = {
        art_status = "generated",
        duration_bytes = 22128,
        frame_count = nil,
        human_reviewed = false,
        id = "pwnglove_boot",
        meets_readability_min = true,
        notes = "Synthesized via tools/audio/sfx_synth.js / synth_v4_sfx.js. Normalized but not pro-mastered. Acceptable for ship; replace if pro audio pass scheduled.",
        path = "sounds/sfx/pwnglove_boot",
        readability_min_pct_screen = 0,
        reference_image = nil,
        reviewed_at = nil,
        reviewer = nil,
        sheet_dimensions = nil,
        target_dimensions = nil,
        target_replacement_version = nil,
        type = "sfx"
    },
    pwnglove_icon = {
        art_status = "final",
        frame_count = 1,
        human_reviewed = true,
        id = "pwnglove_icon",
        meets_readability_min = true,
        notes = "Canonical pin from real PWNGLOVE render. Used by TitleScene + PlaygroundScene.",
        path = "images/pwnglove_icon",
        readability_min_pct_screen = 0.4,
        reference_image = "docs/hakcd_title.png",
        reviewed_at = "2026-05-23",
        reviewer = "cory_k",
        sheet_dimensions = {
            h = 133,
            w = 200
        },
        target_dimensions = {
            h = 133,
            w = 200
        },
        target_replacement_version = nil,
        type = "image"
    },
    step_1 = {
        art_status = "generated",
        duration_bytes = 3130,
        frame_count = nil,
        human_reviewed = false,
        id = "step_1",
        meets_readability_min = true,
        notes = "Synthesized via tools/audio/sfx_synth.js / synth_v4_sfx.js. Normalized but not pro-mastered. Acceptable for ship; replace if pro audio pass scheduled.",
        path = "sounds/sfx/step_1",
        readability_min_pct_screen = 0,
        reference_image = nil,
        reviewed_at = nil,
        reviewer = nil,
        sheet_dimensions = nil,
        target_dimensions = nil,
        target_replacement_version = nil,
        type = "sfx"
    },
    step_2 = {
        art_status = "generated",
        duration_bytes = 3130,
        frame_count = nil,
        human_reviewed = false,
        id = "step_2",
        meets_readability_min = true,
        notes = "Synthesized via tools/audio/sfx_synth.js / synth_v4_sfx.js. Normalized but not pro-mastered. Acceptable for ship; replace if pro audio pass scheduled.",
        path = "sounds/sfx/step_2",
        readability_min_pct_screen = 0,
        reference_image = nil,
        reviewed_at = nil,
        reviewer = nil,
        sheet_dimensions = nil,
        target_dimensions = nil,
        target_replacement_version = nil,
        type = "sfx"
    },
    title = {
        art_status = "final",
        frame_count = 1,
        human_reviewed = true,
        id = "title",
        meets_readability_min = true,
        notes = "Canonical pin from real 23-codes/23Coins repo art. Untouchable.",
        path = "images/title",
        readability_min_pct_screen = 1,
        reference_image = "docs/hakcd_title.png",
        reviewed_at = "2026-05-23",
        reviewer = "cory_k",
        sheet_dimensions = {
            h = 240,
            w = 400
        },
        target_dimensions = {
            h = 240,
            w = 400
        },
        target_replacement_version = nil,
        type = "image"
    },
    title_loop = {
        art_status = "generated",
        duration_bytes = 15879684,
        frame_count = nil,
        human_reviewed = false,
        id = "title_loop",
        meets_readability_min = true,
        notes = "Keygen-scraper sourced, normalized to keygen_loudness_baseline.txt. Not pro-mastered. Acceptable for ship; replace if pro audio pass scheduled.",
        path = "sounds/music/title_loop",
        readability_min_pct_screen = 0,
        reference_image = nil,
        reviewed_at = nil,
        reviewer = nil,
        sheet_dimensions = nil,
        target_dimensions = nil,
        target_replacement_version = nil,
        type = "music"
    },
    tyson_digit_commit = {
        art_status = "generated",
        duration_bytes = 3606,
        frame_count = nil,
        human_reviewed = false,
        id = "tyson_digit_commit",
        meets_readability_min = true,
        notes = "Synthesized via tools/audio/sfx_synth.js / synth_v4_sfx.js. Normalized but not pro-mastered. Acceptable for ship; replace if pro audio pass scheduled.",
        path = "sounds/sfx/tyson_digit_commit",
        readability_min_pct_screen = 0,
        reference_image = nil,
        reviewed_at = nil,
        reviewer = nil,
        sheet_dimensions = nil,
        target_dimensions = nil,
        target_replacement_version = nil,
        type = "sfx"
    },
    tyson_digit_select = {
        art_status = "generated",
        duration_bytes = 1180,
        frame_count = nil,
        human_reviewed = false,
        id = "tyson_digit_select",
        meets_readability_min = true,
        notes = "Synthesized via tools/audio/sfx_synth.js / synth_v4_sfx.js. Normalized but not pro-mastered. Acceptable for ship; replace if pro audio pass scheduled.",
        path = "sounds/sfx/tyson_digit_select",
        readability_min_pct_screen = 0,
        reference_image = nil,
        reviewed_at = nil,
        reviewer = nil,
        sheet_dimensions = nil,
        target_dimensions = nil,
        target_replacement_version = nil,
        type = "sfx"
    },
    tyson_loop = {
        art_status = "generated",
        duration_bytes = 7884020,
        frame_count = nil,
        human_reviewed = false,
        id = "tyson_loop",
        meets_readability_min = true,
        notes = "Keygen-scraper sourced, normalized to keygen_loudness_baseline.txt. Not pro-mastered. Acceptable for ship; replace if pro audio pass scheduled.",
        path = "sounds/music/tyson_loop",
        readability_min_pct_screen = 0,
        reference_image = nil,
        reviewed_at = nil,
        reviewer = nil,
        sheet_dimensions = nil,
        target_dimensions = nil,
        target_replacement_version = nil,
        type = "music"
    },
    tyson_winner = {
        art_status = "generated",
        duration_bytes = 30066,
        frame_count = nil,
        human_reviewed = false,
        id = "tyson_winner",
        meets_readability_min = true,
        notes = "Synthesized via tools/audio/sfx_synth.js / synth_v4_sfx.js. Normalized but not pro-mastered. Acceptable for ship; replace if pro audio pass scheduled.",
        path = "sounds/sfx/tyson_winner",
        readability_min_pct_screen = 0,
        reference_image = nil,
        reviewed_at = nil,
        reviewer = nil,
        sheet_dimensions = nil,
        target_dimensions = nil,
        target_replacement_version = nil,
        type = "sfx"
    }
}

-- ---------- Helpers (consumed by Phase V3 validator + scenes) ----------

function visual_spec.assert_id(asset_id)
    assert(visual_spec[asset_id], "visual_spec: unknown asset id '"..tostring(asset_id).."'")
    return visual_spec[asset_id]
end

function visual_spec.is_final(asset_id)
    local s = visual_spec[asset_id]
    return s and s.art_status == 'final' and s.human_reviewed == true
end

function visual_spec.placeholders()
    local out = {}
    for k, v in pairs(visual_spec) do
        if type(v) == 'table' and v.art_status == 'placeholder' then
            table.insert(out, k)
        end
    end
    table.sort(out)
    return out
end

function visual_spec.failing_readability()
    local out = {}
    for k, v in pairs(visual_spec) do
        if type(v) == 'table' and v.meets_readability_min == false then
            table.insert(out, k)
        end
    end
    table.sort(out)
    return out
end

_G.visual_spec = visual_spec
return visual_spec
